"$schema" = 'https://starship.rs/config-schema.json'

# Define the prompt format using Catppuccin colors
# Note: `fg:<color>` in the separator (``) refers to the *background* color of the *previous* segment.
# Note: `bg:<color>` in the separator (``) refers to the *background* color of the *current* segment.
# Using 'Text' foreground on accent backgrounds for a softer, more harmonious Catppuccin feel.
format = """
[](peach)\
$os\
$username$hostname\
[](bg:yellow fg:peach)\
$directory\
[](fg:yellow bg:teal)\
$git_branch\
$git_status\
[](fg:teal bg:blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue bg:surface0)\
$docker_context\
$conda\
[](fg:surface0 bg:base)\
$time\
[ ](fg:base)\
$line_break$character"""

[os]
disabled = false
# Use peach background and standard 'text' foreground for better harmony
style = "bg:peach fg:text"
format = '[ $symbol ]($style)' # Simplified format slightly

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
# Use peach background and standard 'text' foreground
style_user = "bg:peach fg:text"
style_root = "bg:peach fg:maroon" # Maybe use a different color for root for distinction? Or keep text.
format = '[$user]($style)' # Removed leading space

[hostname]
ssh_only = false
# Use peach background and standard 'text' foreground
style = "bg:peach fg:text"
format = "[@$hostname ]($style)"
disabled = false

[directory]
# Use yellow background and standard 'text' foreground
style = "bg:yellow fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
# Use teal background and standard 'text' foreground
style = "bg:teal fg:text"
format = '[ $symbol $branch ]($style)' # Simplified format, style handles colors

[git_status]
# Use teal background and standard 'text' foreground
style = "bg:teal fg:text"
format = '[($all_status$ahead_behind )]($style)' # Simplified format

[nodejs]
symbol = ""
# Use blue background and standard 'text' foreground
style = "bg:blue fg:text"
format = '[ $symbol( $version) ]($style)' # Simplified format

[c]
symbol = " "
# Use blue background and standard 'text' foreground
style = "bg:blue fg:text"
format = '[ $symbol( $version) ]($style)' # Simplified format

[rust]
symbol = ""
# Use blue background and standard 'text' foreground
style = "bg:blue fg:text"
format = '[ $symbol( $version) ]($style)' # Simplified format

[golang]
symbol = ""
# Use blue background and standard 'text' foreground
style = "bg:blue fg:text"
format = '[ $symbol( $version) ]($style)' # Simplified format

[php]
symbol = ""
# Use blue background and standard 'text' foreground
style = "bg:blue fg:text"
format = '[ $symbol( $version) ]($style)' # Simplified format

[java]
symbol = " "
# Use blue background and standard 'text' foreground
style = "bg:blue fg:text"
format = '[ $symbol( $version) ]($style)' # Simplified format

[kotlin]
symbol = ""
# Use blue background and standard 'text' foreground
style = "bg:blue fg:text"
format = '[ $symbol( $version) ]($style)' # Simplified format

[haskell]
symbol = ""
# Use blue background and standard 'text' foreground
style = "bg:blue fg:text"
format = '[ $symbol( $version) ]($style)' # Simplified format

[python]
symbol = ""
# Use blue background and standard 'text' foreground
style = "bg:blue fg:text"
format = '[ $symbol( $version) ]($style)' # Simplified format

[docker_context]
symbol = ""
# Use surface0 background (muted dark grey)
# Use teal foreground for good visibility and a touch of color here
style = "bg:surface0 fg:teal"
format = '[ $symbol( $context) ]($style)' # Simplified format

[conda]
symbol = "" # Using a different symbol, feel free to change back if you prefer the default
# Use surface0 background
# Use teal foreground to match Docker segment and provide visibility
style = "bg:surface0 fg:teal"
format = '[ $symbol( $environment) ]($style)' # Simplified format

[time]
disabled = false
time_format = "%R" # 24-hour format HH:MM
# Use base background (main dark background)
style = "bg:base fg:text"
# Use text (main light foreground) on base background
format = '[  $time ]($style)' # Simplified format

[line_break]
disabled = false

[character]
disabled = false
# Use Catppuccin accent colors for status symbols - this aligns well already
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'