"$schema" = 'https://starship.rs/config-schema.json'

# Define the prompt format using Catppuccin colors
# Note: `fg:<color>` in the separator (``) refers to the *background* color of the *previous* segment.
# Note: `bg:<color>` in the separator (``) refers to the *background* color of the *current* segment.
format = """
[](peach)\
$os\
$username$hostname\
[](bg:yellow fg:peach)\
$directory\
[](fg:yellow bg:teal)\
$git_branch\
$git_status\
[](fg:teal bg:blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue bg:surface0)\
$docker_context\
$conda\
[](fg:surface0 bg:base)\
$time\
[ ](fg:base)\
$line_break$character"""

[os]
disabled = false
# Use peach background and crust (darkest) foreground for contrast
style = "bg:peach fg:crust"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
# Use peach background and crust (darkest) foreground for contrast
style_user = "bg:peach fg:crust"
style_root = "bg:peach fg:crust"
format = '[ $user]($style)'

[hostname]
ssh_only = false
format = "[@$hostname ]($style)"
# Use peach background and crust (darkest) foreground for contrast
style = "bg:peach fg:crust"
disabled = false

[directory]
# Use yellow background and crust (darkest) foreground for contrast
style = "fg:crust bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
# Use teal background
style = "bg:teal"
# Use crust (darkest) foreground for contrast on teal background
format = '[[ $symbol $branch ](fg:crust bg:teal)]($style)'

[git_status]
# Use teal background
style = "bg:teal"
# Use crust (darkest) foreground for contrast on teal background
format = '[[($all_status$ahead_behind )](fg:crust bg:teal)]($style)'

[nodejs]
symbol = ""
# Use blue background
style = "bg:blue"
# Use crust (darkest) foreground for contrast on blue background
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[docker_context]
symbol = ""
# Use surface0 background (a muted dark grey)
style = "bg:surface0"
# Use teal foreground for visibility on surface0 background
format = '[[ $symbol( $context) ](fg:teal bg:surface0)]($style)'

[conda]
# Use surface0 background
style = "bg:surface0"
# Use teal foreground for visibility on surface0 background
format = '[[ $symbol( $environment) ](fg:teal bg:surface0)]($style)'

[time]
disabled = false
time_format = "%R"
# Use base background (main dark background)
style = "bg:base"
# Use text (main light foreground) on base background
format = '[[  $time ](fg:text bg:base)]($style)'

[line_break]
disabled = false

[character]
disabled = false
# Use Catppuccin accent colors for status symbols
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'