"""Measure a git range in product terms: changed lines, changed files, churn ranking."""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from dataclasses import dataclass
import json


EXCLUSION_CLASSES = ("lockfile", "generated", "artifact")
LOCKFILE_SUFFIX = b".lock"
LOCKFILE_NAMES = frozenset(
    {b"package-lock.json", b"bun.lockb", b"go.sum", b"pnpm-lock.yaml"}
)
GENERATED_MARKERS = (b"<auto-generated>", b"// Code generated by")
HEADER_SCAN_LINES = 5
HEADER_SCAN_BYTES = 8192


@dataclass(frozen=True)
class DiffRow:
    """One row of a git range, keyed by its destination path.

    `path` is the row's destination path as raw bytes, repository-root-relative:
    the new path on a rename and the single printed path everywhere else,
    including a deletion. `additions`/`deletions` are None on a binary row,
    because git prints `-` rather than a count.
    """

    path: bytes
    additions: int | None
    deletions: int | None
    header: bytes | None = None

    @property
    def binary(self) -> bool:
        """True when git reported no line counts for this row."""
        return self.additions is None or self.deletions is None

    @property
    def churn(self) -> int:
        """Additions plus deletions; zero for a binary row, which has no counts."""
        if self.binary:
            return 0
        return self.additions + self.deletions


@dataclass(frozen=True)
class ScopeResult:
    """The product measurement: ranked product rows plus per-class exclusion counts."""

    files: tuple[DiffRow, ...]
    excluded: dict[str, int]

    @property
    def changed_lines(self) -> int:
        """Total churn over the product rows."""
        return sum(row.churn for row in self.files)

    @property
    def changed_files(self) -> int:
        """Number of product rows."""
        return len(self.files)


def _is_lockfile(path: bytes) -> bool:
    """True when the row's basename is a dependency lockfile."""
    basename = path.rpartition(b"/")[2]
    return basename.endswith(LOCKFILE_SUFFIX) or basename in LOCKFILE_NAMES


def _is_generated(row: DiffRow) -> bool:
    """True when the row's first HEADER_SCAN_LINES lines carry a generated marker."""
    if row.binary or not row.header:
        return False
    window = b"\n".join(row.header.split(b"\n")[:HEADER_SCAN_LINES])
    return any(marker in window for marker in GENERATED_MARKERS)


def _is_artifact(path: bytes, artifact_paths: Sequence[bytes]) -> bool:
    """True when the path equals an artifact value or lives under one.

    No filesystem access, so a deleted path classifies exactly like a live one.
    """
    return any(
        path == value or path.startswith(value + b"/") for value in artifact_paths
    )


def classify_row(row: DiffRow, artifact_paths: Sequence[bytes]) -> str | None:
    """Return the first exclusion class this row matches, or None when it is product.

    The order is fixed: lockfile, then generated, then artifact. First match wins,
    so each dropped row is counted exactly once.
    """
    if _is_lockfile(row.path):
        return "lockfile"
    if _is_generated(row):
        return "generated"
    if _is_artifact(row.path, artifact_paths):
        return "artifact"
    return None


def _rank(rows: Iterable[DiffRow]) -> tuple[DiffRow, ...]:
    """Rank by churn descending, then raw path bytes ascending -- a total order."""
    return tuple(sorted(rows, key=lambda row: (-row.churn, row.path)))


def scope_rows(rows: Iterable[DiffRow], artifact_paths: Sequence[bytes]) -> ScopeResult:
    """Apply the three exclusions once per row and rank what survives."""
    excluded = {name: 0 for name in EXCLUSION_CLASSES}
    product: list[DiffRow] = []
    for row in rows:
        found = classify_row(row, artifact_paths)
        if found is None:
            product.append(row)
        else:
            excluded[found] += 1
    return ScopeResult(files=_rank(product), excluded=excluded)


def _decode(path: bytes) -> str:
    """Decode a raw path at the output boundary, preserving undecodable bytes."""
    return path.decode("utf-8", errors="surrogateescape")


def format_json(range_text: str, result: ScopeResult) -> str:
    """Render the measurement as one compact, key-sorted, pure-ASCII JSON line.

    ensure_ascii is load-bearing: it renders a surrogate-escaped path as a
    \\udcff escape instead of raising on the write.
    """
    payload = {
        "range": range_text,
        "product": {
            "changed_lines": result.changed_lines,
            "changed_files": result.changed_files,
        },
        "files": [
            {
                "path": _decode(row.path),
                "changed_lines": row.churn,
                "binary": row.binary,
            }
            for row in result.files
        ],
        "excluded": {name: result.excluded[name] for name in EXCLUSION_CLASSES},
    }
    return (
        json.dumps(
            payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True
        )
        + "\n"
    )


def format_text(result: ScopeResult) -> str:
    """Render the measurement as quotable prose; the text form omits the range."""
    lines = [
        f"product: {result.changed_lines} lines, {result.changed_files} files",
        "excluded: "
        + ", ".join(f"{result.excluded[name]} {name}" for name in EXCLUSION_CLASSES),
    ]
    for row in result.files:
        suffix = " (binary)" if row.binary else ""
        lines.append(f"  {row.churn}  {_decode(row.path)}{suffix}")
    return "".join(f"{line}\n" for line in lines)
