#!/usr/bin/env python3
"""Measure a git range in product terms: changed lines, changed files, churn ranking."""

from __future__ import annotations

import argparse
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, replace
import json
from pathlib import Path
import subprocess
import sys


EXCLUSION_CLASSES = ("lockfile", "generated", "artifact")
LOCKFILE_SUFFIX = b".lock"
LOCKFILE_NAMES = frozenset(
    {b"package-lock.json", b"bun.lockb", b"go.sum", b"pnpm-lock.yaml"}
)
GENERATED_MARKERS = (b"<auto-generated>", b"// Code generated by")
HEADER_SCAN_LINES = 5
HEADER_SCAN_BYTES = 8192


class DiffScopeError(Exception):
    """A condition under which no measurement can be produced; main exits 1."""


@dataclass(frozen=True)
class DiffRow:
    """One row of a git range, keyed by its destination path.

    `path` is the row's destination path as raw bytes, repository-root-relative:
    the new path on a rename and the single printed path everywhere else,
    including a deletion. `additions`/`deletions` are None on a binary row,
    because git prints `-` rather than a count.
    """

    path: bytes
    additions: int | None
    deletions: int | None
    header: bytes | None = None

    @property
    def binary(self) -> bool:
        """True when git reported no line counts for this row."""
        return self.additions is None or self.deletions is None

    @property
    def churn(self) -> int:
        """Additions plus deletions; zero for a binary row, which has no counts."""
        if self.binary:
            return 0
        return self.additions + self.deletions


@dataclass(frozen=True)
class ScopeResult:
    """The product measurement: ranked product rows plus per-class exclusion counts."""

    files: tuple[DiffRow, ...]
    excluded: dict[str, int]

    @property
    def changed_lines(self) -> int:
        """Total churn over the product rows."""
        return sum(row.churn for row in self.files)

    @property
    def changed_files(self) -> int:
        """Number of product rows."""
        return len(self.files)


def _is_lockfile(path: bytes) -> bool:
    """True when the row's basename is a dependency lockfile."""
    basename = path.rpartition(b"/")[2]
    return basename.endswith(LOCKFILE_SUFFIX) or basename in LOCKFILE_NAMES


def _is_generated(row: DiffRow) -> bool:
    """True when the row's first HEADER_SCAN_LINES lines carry a generated marker."""
    if row.binary or not row.header:
        return False
    window = b"\n".join(row.header.split(b"\n")[:HEADER_SCAN_LINES])
    return any(marker in window for marker in GENERATED_MARKERS)


def _is_artifact(path: bytes, artifact_paths: Sequence[bytes]) -> bool:
    """True when the path equals an artifact value or lives under one.

    No filesystem access, so a deleted path classifies exactly like a live one.
    """
    return any(
        path == value or path.startswith(value + b"/") for value in artifact_paths
    )


def classify_row(row: DiffRow, artifact_paths: Sequence[bytes]) -> str | None:
    """Return the first exclusion class this row matches, or None when it is product.

    The order is fixed: lockfile, then generated, then artifact. First match wins,
    so each dropped row is counted exactly once.
    """
    if _is_lockfile(row.path):
        return "lockfile"
    if _is_generated(row):
        return "generated"
    if _is_artifact(row.path, artifact_paths):
        return "artifact"
    return None


def _rank(rows: Iterable[DiffRow]) -> tuple[DiffRow, ...]:
    """Rank by churn descending, then raw path bytes ascending -- a total order."""
    return tuple(sorted(rows, key=lambda row: (-row.churn, row.path)))


def scope_rows(rows: Iterable[DiffRow], artifact_paths: Sequence[bytes]) -> ScopeResult:
    """Apply the three exclusions once per row and rank what survives."""
    excluded = {name: 0 for name in EXCLUSION_CLASSES}
    product: list[DiffRow] = []
    for row in rows:
        found = classify_row(row, artifact_paths)
        if found is None:
            product.append(row)
        else:
            excluded[found] += 1
    return ScopeResult(files=_rank(product), excluded=excluded)


def _decode(path: bytes) -> str:
    """Decode a raw path at the output boundary, preserving undecodable bytes."""
    return path.decode("utf-8", errors="surrogateescape")


def format_json(range_text: str, result: ScopeResult) -> str:
    """Render the measurement as one compact, key-sorted, pure-ASCII JSON line.

    ensure_ascii is load-bearing: it renders a surrogate-escaped path as a
    \\udcff escape instead of raising on the write.
    """
    payload = {
        "range": range_text,
        "product": {
            "changed_lines": result.changed_lines,
            "changed_files": result.changed_files,
        },
        "files": [
            {
                "path": _decode(row.path),
                "changed_lines": row.churn,
                "binary": row.binary,
            }
            for row in result.files
        ],
        "excluded": {name: result.excluded[name] for name in EXCLUSION_CLASSES},
    }
    return (
        json.dumps(
            payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True
        )
        + "\n"
    )


def format_text(result: ScopeResult) -> str:
    """Render the measurement as quotable prose; the text form omits the range."""
    lines = [
        f"product: {result.changed_lines} lines, {result.changed_files} files",
        "excluded: "
        + ", ".join(f"{result.excluded[name]} {name}" for name in EXCLUSION_CLASSES),
    ]
    for row in result.files:
        suffix = " (binary)" if row.binary else ""
        lines.append(f"  {row.churn}  {_decode(row.path)}{suffix}")
    return "".join(f"{line}\n" for line in lines)


def _git(root: Path, *arguments: str, stdin_payload: bytes | None = None) -> bytes:
    """Run one git command by argv and return its raw stdout.

    Never `shell=True` and never `text=True`: stdout carries raw path bytes,
    and no path argument may ever meet a shell.
    """
    try:
        completed = subprocess.run(
            ["git", *arguments],
            cwd=str(root),
            input=stdin_payload,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
    except FileNotFoundError:
        raise DiffScopeError("git executable not found on PATH") from None
    if completed.returncode != 0:
        detail = completed.stderr.decode("utf-8", errors="replace").strip()
        raise DiffScopeError(f"git {' '.join(arguments)} failed: {detail}")
    return completed.stdout


def parse_range(text: str) -> tuple[str, str]:
    """Split `<base>..<head>`, leaving git the authority on revision syntax.

    The three-dot check comes first: `"a...b".count("..")` is 1, so a symmetric
    difference survives a naive "exactly one `..`" test (D10).
    """
    if "..." in text:
        raise DiffScopeError(f"not a two-dot range: {text}")
    parts = text.split("..")
    if len(parts) != 2:
        raise DiffScopeError(f"not a two-dot range: {text}")
    base, head = parts
    if not base or not head:
        raise DiffScopeError(f"range is missing a side: {text}")
    return base, head


def normalize_artifact_path(value: str) -> bytes:
    """Normalise one --artifact-path to repository-root-relative raw bytes.

    Root-relative because git reports numstat paths root-relative even when it
    is run from a subdirectory (D8).
    """
    if value.startswith("/"):
        raise DiffScopeError(f"--artifact-path must be repository-relative: {value}")
    cleaned = value
    while cleaned.startswith("./"):
        cleaned = cleaned[2:]
    cleaned = cleaned.rstrip("/")
    if cleaned in ("", "."):
        raise DiffScopeError(f"--artifact-path is empty: {value}")
    if ".." in cleaned.split("/"):
        raise DiffScopeError(f"--artifact-path escapes the repository: {value}")
    return cleaned.encode("utf-8", errors="surrogateescape")


def _split_records(payload: bytes) -> list[bytes]:
    """Split a -z stream into tokens, dropping the trailing terminator's empty tail."""
    tokens = payload.split(b"\0")
    if tokens and tokens[-1] == b"":
        tokens.pop()
    return tokens


def _parse_count(text: bytes) -> int | None:
    """One numstat count; git prints `-` for a binary row, which has no counts."""
    if text == b"-":
        return None
    try:
        return int(text)
    except ValueError:
        raise DiffScopeError(f"unparsable numstat count {text!r}") from None


def parse_numstat(payload: bytes) -> tuple[DiffRow, ...]:
    """Parse `git diff --numstat -z -M` into rows keyed by destination path."""
    tokens = _split_records(payload)
    rows: list[DiffRow] = []
    index = 0
    while index < len(tokens):
        # split(b"\t", 2) -- a tab is a legal filename byte and -z emits path bytes
        # verbatim, so only the first two tabs are field separators (D22).
        fields = tokens[index].split(b"\t", 2)
        if len(fields) != 3:
            raise DiffScopeError(f"unparsable numstat record {tokens[index]!r}")
        # A count record is exactly <add>\t<del>\t<path>; anything else is corrupt.
        additions_text, deletions_text, path = fields
        if path == b"":
            # Rename or copy: git emits <record>\0<old>\0<new>\0. The destination is
            # the SECOND following token -- tokens[index + 1] is the OLD path (D21).
            if index + 2 >= len(tokens):
                raise DiffScopeError(
                    f"truncated numstat rename record {tokens[index]!r}"
                )
            path = tokens[index + 2]
            index += 3
        else:
            index += 1
        rows.append(
            DiffRow(
                path=path,
                additions=_parse_count(additions_text),
                deletions=_parse_count(deletions_text),
            )
        )
    return tuple(rows)


def parse_name_status(payload: bytes) -> dict[bytes, bytes]:
    """Parse `git diff --name-status -z -M` into {destination path: status}."""
    tokens = _split_records(payload)
    statuses: dict[bytes, bytes] = {}
    index = 0
    while index < len(tokens):
        status = tokens[index]
        # R and C carry two paths; the destination is the second, matching numstat.
        consumed = 2 if status[:1] in (b"R", b"C") else 1
        if index + consumed >= len(tokens):
            raise DiffScopeError(f"truncated name-status record {status!r}")
        statuses[tokens[index + consumed]] = status
        index += 1 + consumed
    return statuses


def _parse_batch(payload: bytes, expected: int) -> list[bytes]:
    """Return one header window per request, in request order.

    Responses are consumed by their declared byte size, never by a delimiter,
    so content holding newlines cannot desynchronise the stream.
    """
    windows: list[bytes] = []
    position = 0
    for _ in range(expected):
        newline = payload.find(b"\n", position)
        if newline < 0:
            raise DiffScopeError("truncated cat-file batch response")
        header = payload[position:newline]
        # Parse defensively and raise DiffScopeError for ANYTHING unparsable (D23).
        # A `missing` answer echoes the request verbatim, so for a path holding a
        # newline the find() above stops inside the path and `header` is a fragment
        # that neither ends with b" missing" nor rsplits into three parts. Letting
        # that reach the unpack raises ValueError, which escapes main's
        # `except DiffScopeError` and dies with a traceback instead of the
        # `diff-scope: ...` message every CLI error test asserts on.
        parts = header.rsplit(b" ", 2)
        if header.endswith(b" missing") or len(parts) != 3:
            # We only ever ask for a side git's own --name-status said exists,
            # so a missing answer is a hard error, never a fallback (D7).
            raise DiffScopeError(f"git reported missing content for {header!r}")
        object_type, size_text = parts[1:]
        try:
            size = int(size_text)
        except ValueError:
            raise DiffScopeError(f"unparsable cat-file header {header!r}") from None
        start = newline + 1
        end = start + size
        if end > len(payload):
            raise DiffScopeError("truncated cat-file batch content")
        # Clip to this response first, then to the byte bound, so a response
        # shorter than HEADER_SCAN_BYTES never bleeds into the next one. A
        # non-blob type (a submodule gitlink resolves to a commit) yields b"",
        # which the classifier reads as not generated.
        windows.append(
            payload[start:end][:HEADER_SCAN_BYTES] if object_type == b"blob" else b""
        )
        position = end + 1  # one newline terminates each response
    return windows


def read_headers(
    root: Path,
    base: str,
    head: str,
    rows: Sequence[DiffRow],
    statuses: dict[bytes, bytes],
) -> dict[bytes, bytes]:
    """Read one header window per row whose content could still matter.

    Binary and lockfile rows are never queried: a lockfile is excluded before
    the generated check runs, so its content can never change the answer. An
    artifact row is checked *after* generated, so it must still be read.
    """
    requests: list[bytes] = []
    paths: list[bytes] = []
    for row in rows:
        if row.binary or _is_lockfile(row.path):
            continue
        status = statuses.get(row.path)
        if status is None:
            raise DiffScopeError(f"no --name-status row for {row.path!r}")
        # The content side comes from the status, never from a guess: a deletion
        # exists only on the base side.
        revision = base if status[:1] == b"D" else head
        requests.append(
            revision.encode("utf-8", errors="surrogateescape") + b":" + row.path + b"\0"
        )
        paths.append(row.path)
    if not requests:
        return {}
    payload = _git(root, "cat-file", "--batch", "-z", stdin_payload=b"".join(requests))
    return dict(zip(paths, _parse_batch(payload, len(paths))))


def measure(
    root: Path, base: str, head: str, artifact_paths: Sequence[bytes]
) -> ScopeResult:
    """Return the product measurement for base..head, applying the three exclusions."""
    range_argument = f"{base}..{head}"
    # -M explicitly, so the measurement never depends on the caller's diff.renames (D3).
    rows = parse_numstat(_git(root, "diff", "--numstat", "-z", "-M", range_argument))
    if not rows:
        return scope_rows((), artifact_paths)
    statuses = parse_name_status(
        _git(root, "diff", "--name-status", "-z", "-M", range_argument)
    )
    headers = read_headers(root, base, head, rows, statuses)
    return scope_rows(
        (replace(row, header=headers.get(row.path)) for row in rows), artifact_paths
    )


def _validate_root(root: Path) -> None:
    """Refuse anything that is not a git work tree."""
    message = f"--root is not a git work tree: {root}"
    if not root.is_dir():
        raise DiffScopeError(message)
    try:
        answer = _git(root, "rev-parse", "--is-inside-work-tree")
    except DiffScopeError as error:
        # Keep git's own diagnostic: git-not-on-PATH, an unreadable .git and a
        # corrupt object store are not --root mistakes, and collapsing them into
        # this sentence would point the operator at the wrong thing.
        raise DiffScopeError(f"{message} ({error})") from None
    if answer.strip() != b"true":
        raise DiffScopeError(message)


def _emit(payload: str) -> None:
    """Write output as bytes; print() raises on a surrogate-escaped path (D19)."""
    sys.stdout.buffer.write(payload.encode("utf-8", errors="surrogateescape"))
    sys.stdout.buffer.flush()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="diff-scope", description=__doc__)
    parser.add_argument("range", help="the range to measure, as <base>..<head>")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="the git work tree to measure in (default: the current directory)",
    )
    parser.add_argument(
        "--artifact-path",
        action="append",
        default=[],
        metavar="PATH",
        help="repository-relative path holding this run's own artifacts; repeatable",
    )
    parser.add_argument(
        "--format",
        choices=("json", "text"),
        default="json",
        help="output format (default: json)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        base, head = parse_range(args.range)
        artifact_paths = tuple(
            normalize_artifact_path(value) for value in args.artifact_path
        )
        root = Path(args.root)
        _validate_root(root)
        result = measure(root, base, head, artifact_paths)
    except DiffScopeError as error:
        print(f"diff-scope: {error}", file=sys.stderr)
        return 1
    _emit(
        format_json(args.range, result)
        if args.format == "json"
        else format_text(result)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
