"""Contracts for the diff-scope product-accounting helper.

Two layers, per the design's Test seams section. The classifier layer imports
scripts/diff-scope.py directly and drives the pure classifier over synthetic
rows shaped the way the git layer actually emits them -- a binary row carrying
absent counts rather than zeros, a rename row already reduced to its
destination path. The CLI layer (added with the git layer) runs the script as a
subprocess against scratch git repositories under a TemporaryDirectory; it
talks to no network and touches no repository but its own.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import sys
import unittest


REPO_ROOT = Path(__file__).parents[4]
SCRIPT = REPO_ROOT / "home/common/agent-skills/scripts/diff-scope.py"


def load_module():
    """Import scripts/diff-scope.py as a module.

    The sys.modules registration is required, not decorative: the script uses
    `from __future__ import annotations`, so its dataclass field annotations are
    strings, and dataclasses resolves them through sys.modules[cls.__module__].
    Without the registration every dataclass in the module raises AttributeError
    at import. test_agent_model_matrix.py omits this line only because the script
    it loads defines no dataclass.
    """
    spec = importlib.util.spec_from_file_location("diff_scope", SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import {SCRIPT}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class DiffScopeClassifierTest(unittest.TestCase):
    """The pure classifier, over rows shaped the way the git layer emits them."""

    @classmethod
    def setUpClass(cls):
        cls.module = load_module()

    def row(self, path, additions=1, deletions=1, header=None):
        return self.module.DiffRow(
            path=path, additions=additions, deletions=deletions, header=header
        )

    def scope(self, rows, artifact_paths=()):
        return self.module.scope_rows(rows, artifact_paths)

    # --- lockfile class --------------------------------------------------

    def test_lockfile_row_is_excluded_while_its_product_sibling_survives(self):
        result = self.scope(
            [self.row(b"pnpm-lock.yaml", 40, 2), self.row(b"src/app.py", 3, 1)]
        )
        self.assertEqual([row.path for row in result.files], [b"src/app.py"])
        self.assertEqual(result.changed_lines, 4)
        self.assertEqual(result.changed_files, 1)
        self.assertEqual(result.excluded["lockfile"], 1)

    def test_every_lockfile_spelling_is_recognised(self):
        for path in (
            b"pnpm-lock.yaml",
            b"package-lock.json",
            b"bun.lockb",
            b"go.sum",
            b"Cargo.lock",
            b"deep/nested/Gemfile.lock",
        ):
            with self.subTest(path=path):
                result = self.scope([self.row(path, 10, 10)])
                self.assertEqual(result.files, ())
                self.assertEqual(result.excluded["lockfile"], 1)

    def test_a_path_merely_containing_lock_is_product(self):
        result = self.scope([self.row(b"src/locking.py", 2, 0)])
        self.assertEqual([row.path for row in result.files], [b"src/locking.py"])
        self.assertEqual(result.excluded["lockfile"], 0)

    # --- generated class -------------------------------------------------

    def test_generated_row_is_excluded_while_its_product_sibling_survives(self):
        result = self.scope(
            [
                self.row(
                    b"api/types.ts",
                    90,
                    10,
                    header=b"// Code generated by protoc-gen-ts.\nexport {};\n",
                ),
                self.row(b"src/app.py", 3, 1),
            ]
        )
        self.assertEqual([row.path for row in result.files], [b"src/app.py"])
        self.assertEqual(result.changed_lines, 4)
        self.assertEqual(result.changed_files, 1)
        self.assertEqual(result.excluded["generated"], 1)

    def test_auto_generated_marker_is_recognised(self):
        result = self.scope([self.row(b"Model.cs", 5, 5, header=b"// <auto-generated>\n")])
        self.assertEqual(result.files, ())
        self.assertEqual(result.excluded["generated"], 1)

    def test_marker_below_the_fifth_line_stays_product(self):
        # ship-issue/SYNC.md carries "// Code generated by" as prose in a table.
        # A whole-file scan would classify a hand-written skill document as
        # machine-generated and silently shrink every branch that edits it.
        header = b"\n".join(
            [b"one", b"two", b"three", b"four", b"five", b"// Code generated by tool"]
        )
        result = self.scope([self.row(b"skills/ship-issue/SYNC.md", 7, 1, header=header)])
        self.assertEqual(
            [row.path for row in result.files], [b"skills/ship-issue/SYNC.md"]
        )
        self.assertEqual(result.excluded["generated"], 0)

    def test_a_binary_row_is_never_classified_as_generated(self):
        result = self.scope(
            [self.row(b"assets/logo.png", None, None, header=b"// Code generated by x")]
        )
        self.assertEqual([row.path for row in result.files], [b"assets/logo.png"])
        self.assertEqual(result.excluded["generated"], 0)

    def test_a_row_whose_header_was_not_read_is_product(self):
        result = self.scope([self.row(b"src/app.py", 2, 0, header=None)])
        self.assertEqual([row.path for row in result.files], [b"src/app.py"])
        self.assertEqual(result.excluded["generated"], 0)

    # --- artifact class and the carve-out --------------------------------

    def test_only_the_named_artifact_is_excluded(self):
        rows = [
            self.row(b".claude/specs/2026-08-16-diff-scope-helper-design.md", 120, 0),
            self.row(b".claude/specs/2026-01-01-historical-design.md", 30, 4),
            self.row(b"src/app.py", 3, 1),
        ]
        result = self.scope(
            rows, (b".claude/specs/2026-08-16-diff-scope-helper-design.md",)
        )
        self.assertEqual(
            [row.path for row in result.files],
            [b".claude/specs/2026-01-01-historical-design.md", b"src/app.py"],
        )
        self.assertEqual(result.changed_lines, 38)
        self.assertEqual(result.excluded["artifact"], 1)

    def test_without_artifact_paths_a_historical_artifact_still_counts(self):
        rows = [
            self.row(b".claude/specs/2026-08-16-diff-scope-helper-design.md", 120, 0),
            self.row(b".claude/specs/2026-01-01-historical-design.md", 30, 4),
            self.row(b"src/app.py", 3, 1),
        ]
        result = self.scope(rows)
        self.assertEqual(result.changed_files, 3)
        self.assertEqual(result.changed_lines, 158)
        self.assertEqual(result.excluded["artifact"], 0)

    def test_artifact_prefix_matches_a_directory_not_a_sibling_prefix(self):
        rows = [
            self.row(b".claude/plans/run.md", 10, 0),
            self.row(b".claude/plans-archive/old.md", 7, 0),
        ]
        result = self.scope(rows, (b".claude/plans",))
        self.assertEqual(
            [row.path for row in result.files], [b".claude/plans-archive/old.md"]
        )
        self.assertEqual(result.excluded["artifact"], 1)

    # --- ranking, sums, and the zero cases --------------------------------

    def test_ranking_is_churn_descending_with_a_raw_byte_tie_break(self):
        rows = [
            self.row(b"b.txt", 5, 5),
            self.row(b"a.txt", 5, 5),
            self.row(b"c.txt", 9, 0),
        ]
        result = self.scope(rows)
        self.assertEqual(
            [row.path for row in result.files], [b"a.txt", b"b.txt", b"c.txt"]
        )
        self.assertEqual([row.churn for row in result.files], [10, 10, 9])

    def test_ranking_does_not_depend_on_input_order(self):
        forward = [
            self.row(b"a.txt", 5, 5),
            self.row(b"b.txt", 5, 5),
            self.row(b"c.txt", 9, 0),
        ]
        reverse = list(reversed(forward))
        self.assertEqual(
            [row.path for row in self.scope(forward).files],
            [row.path for row in self.scope(reverse).files],
        )

    def test_a_binary_row_is_one_product_file_and_zero_product_lines(self):
        result = self.scope(
            [self.row(b"assets/logo.png", None, None), self.row(b"src/app.py", 3, 1)]
        )
        self.assertEqual(result.changed_files, 2)
        self.assertEqual(result.changed_lines, 4)
        binary_row = next(
            row for row in result.files if row.path == b"assets/logo.png"
        )
        self.assertTrue(binary_row.binary)
        self.assertEqual(binary_row.churn, 0)

    def test_a_pure_rename_is_a_zero_churn_row_that_is_not_binary(self):
        result = self.scope([self.row(b"pkg/new.txt", 0, 0)])
        self.assertEqual(result.files[0].churn, 0)
        self.assertFalse(result.files[0].binary)
        self.assertEqual(result.changed_files, 1)

    def test_a_range_of_only_excluded_rows_measures_zero(self):
        rows = [
            self.row(b"pnpm-lock.yaml", 40, 2),
            self.row(b"api/types.ts", 90, 10, header=b"// Code generated by protoc.\n"),
            self.row(b".claude/plans/run.md", 200, 0),
        ]
        result = self.scope(rows, (b".claude/plans/run.md",))
        self.assertEqual(result.files, ())
        self.assertEqual(result.changed_lines, 0)
        self.assertEqual(result.changed_files, 0)
        self.assertEqual(
            result.excluded, {"lockfile": 1, "generated": 1, "artifact": 1}
        )

    def test_an_empty_row_set_measures_zero(self):
        result = self.scope([])
        self.assertEqual(result.files, ())
        self.assertEqual(result.changed_lines, 0)
        self.assertEqual(result.changed_files, 0)
        self.assertEqual(
            result.excluded, {"lockfile": 0, "generated": 0, "artifact": 0}
        )

    def test_each_row_is_counted_under_exactly_one_class(self):
        # A generated file under an artifact path counts once, as generated:
        # the order is lockfile -> generated -> artifact and the first match wins.
        rows = [
            self.row(b".claude/plans/gen.md", 10, 0, header=b"<auto-generated>\n"),
            self.row(b".claude/plans/Cargo.lock", 4, 4),
            self.row(b"src/app.py", 3, 1),
        ]
        result = self.scope(rows, (b".claude/plans",))
        self.assertEqual(
            result.excluded, {"lockfile": 1, "generated": 1, "artifact": 0}
        )
        self.assertEqual(
            len(result.files) + sum(result.excluded.values()), len(rows)
        )

    # --- output formats ---------------------------------------------------

    def test_json_output_is_compact_key_sorted_and_ascii(self):
        result = self.scope(
            [self.row(b"src/app.py", 3, 1), self.row(b"assets/logo.png", None, None)]
        )
        self.assertEqual(
            self.module.format_json("base..head", result),
            '{"excluded":{"artifact":0,"generated":0,"lockfile":0},'
            '"files":[{"binary":false,"changed_lines":4,"path":"src/app.py"},'
            '{"binary":true,"changed_lines":0,"path":"assets/logo.png"}],'
            '"product":{"changed_files":2,"changed_lines":4},'
            '"range":"base..head"}\n',
        )

    def test_a_non_utf8_path_survives_json_encoding(self):
        # APFS cannot hold such a name, so this hazard is only reachable here
        # and never from the CLI layer's scratch repositories (D19).
        result = self.scope([self.row(b"src/bad-\xff.py", 2, 0)])
        payload = self.module.format_json("base..head", result)
        self.assertEqual(payload, payload.encode("ascii").decode("ascii"))
        self.assertEqual(
            json.loads(payload)["files"][0]["path"], "src/bad-\udcff.py"
        )

    def test_text_output_names_the_totals_and_ranks_the_files(self):
        result = self.scope(
            [
                self.row(b"src/app.py", 3, 1),
                self.row(b"assets/logo.png", None, None),
                self.row(b"pnpm-lock.yaml", 40, 2),
            ]
        )
        self.assertEqual(
            self.module.format_text(result),
            "product: 4 lines, 2 files\n"
            "excluded: 1 lockfile, 0 generated, 0 artifact\n"
            "  4  src/app.py\n"
            "  0  assets/logo.png (binary)\n",
        )


if __name__ == "__main__":
    unittest.main()
