"""Contracts for the diff-scope product-accounting helper.

Two layers, per the design's Test seams section. The classifier layer imports
scripts/diff-scope.py directly and drives the pure classifier over synthetic
rows shaped the way the git layer actually emits them -- a binary row carrying
absent counts rather than zeros, a rename row already reduced to its
destination path. The CLI layer (added with the git layer) runs the script as a
subprocess against scratch git repositories under a TemporaryDirectory; it
talks to no network and touches no repository but its own.
"""

from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
import unittest.mock


REPO_ROOT = Path(__file__).parents[4]
SCRIPT = REPO_ROOT / "home/common/agent-skills/scripts/diff-scope.py"


def load_module():
    """Import scripts/diff-scope.py as a module.

    The sys.modules registration is required, not decorative: the script uses
    `from __future__ import annotations`, so its dataclass field annotations are
    strings, and dataclasses resolves them through sys.modules[cls.__module__].
    Without the registration every dataclass in the module raises AttributeError
    at import. test_agent_model_matrix.py omits this line only because the script
    it loads defines no dataclass.
    """
    spec = importlib.util.spec_from_file_location("diff_scope", SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import {SCRIPT}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class DiffScopeClassifierTest(unittest.TestCase):
    """The pure classifier, over rows shaped the way the git layer emits them."""

    @classmethod
    def setUpClass(cls):
        cls.module = load_module()

    def row(self, path, additions=1, deletions=1, header=None):
        return self.module.DiffRow(
            path=path, additions=additions, deletions=deletions, header=header
        )

    def scope(self, rows, artifact_paths=()):
        return self.module.scope_rows(rows, artifact_paths)

    # --- lockfile class --------------------------------------------------

    def test_lockfile_row_is_excluded_while_its_product_sibling_survives(self):
        result = self.scope(
            [self.row(b"pnpm-lock.yaml", 40, 2), self.row(b"src/app.py", 3, 1)]
        )
        self.assertEqual([row.path for row in result.files], [b"src/app.py"])
        self.assertEqual(result.changed_lines, 4)
        self.assertEqual(result.changed_files, 1)
        self.assertEqual(result.excluded["lockfile"], 1)

    def test_every_lockfile_spelling_is_recognised(self):
        for path in (
            b"pnpm-lock.yaml",
            b"package-lock.json",
            b"bun.lockb",
            b"go.sum",
            b"Cargo.lock",
            b"deep/nested/Gemfile.lock",
        ):
            with self.subTest(path=path):
                result = self.scope([self.row(path, 10, 10)])
                self.assertEqual(result.files, ())
                self.assertEqual(result.excluded["lockfile"], 1)

    def test_a_path_merely_containing_lock_is_product(self):
        result = self.scope([self.row(b"src/locking.py", 2, 0)])
        self.assertEqual([row.path for row in result.files], [b"src/locking.py"])
        self.assertEqual(result.excluded["lockfile"], 0)

    # --- generated class -------------------------------------------------

    def test_generated_row_is_excluded_while_its_product_sibling_survives(self):
        result = self.scope(
            [
                self.row(
                    b"api/types.ts",
                    90,
                    10,
                    header=b"// Code generated by protoc-gen-ts.\nexport {};\n",
                ),
                self.row(b"src/app.py", 3, 1),
            ]
        )
        self.assertEqual([row.path for row in result.files], [b"src/app.py"])
        self.assertEqual(result.changed_lines, 4)
        self.assertEqual(result.changed_files, 1)
        self.assertEqual(result.excluded["generated"], 1)

    def test_auto_generated_marker_is_recognised(self):
        result = self.scope([self.row(b"Model.cs", 5, 5, header=b"// <auto-generated>\n")])
        self.assertEqual(result.files, ())
        self.assertEqual(result.excluded["generated"], 1)

    def test_marker_on_the_fifth_line_is_generated(self):
        # The boundary itself, not just one side of it: HEADER_SCAN_LINES is 5,
        # so the fifth line is the last one that counts. Without this case the
        # constant can be narrowed to 4 with every other assertion still green.
        header = b"\n".join(
            [b"one", b"two", b"three", b"four", b"// Code generated by tool"]
        )
        result = self.scope([self.row(b"api/types.ts", 5, 5, header=header)])
        self.assertEqual(result.files, ())
        self.assertEqual(result.excluded["generated"], 1)

    def test_marker_below_the_fifth_line_stays_product(self):
        # ship-issue/SYNC.md carries "// Code generated by" as prose in a table.
        # A whole-file scan would classify a hand-written skill document as
        # machine-generated and silently shrink every branch that edits it.
        header = b"\n".join(
            [b"one", b"two", b"three", b"four", b"five", b"// Code generated by tool"]
        )
        result = self.scope([self.row(b"skills/ship-issue/SYNC.md", 7, 1, header=header)])
        self.assertEqual(
            [row.path for row in result.files], [b"skills/ship-issue/SYNC.md"]
        )
        self.assertEqual(result.excluded["generated"], 0)

    def test_a_binary_row_is_never_classified_as_generated(self):
        result = self.scope(
            [self.row(b"assets/logo.png", None, None, header=b"// Code generated by x")]
        )
        self.assertEqual([row.path for row in result.files], [b"assets/logo.png"])
        self.assertEqual(result.excluded["generated"], 0)

    def test_a_row_whose_header_was_not_read_is_product(self):
        result = self.scope([self.row(b"src/app.py", 2, 0, header=None)])
        self.assertEqual([row.path for row in result.files], [b"src/app.py"])
        self.assertEqual(result.excluded["generated"], 0)

    # --- artifact class and the carve-out --------------------------------

    def test_only_the_named_artifact_is_excluded(self):
        rows = [
            self.row(b".claude/specs/2026-08-16-diff-scope-helper-design.md", 120, 0),
            self.row(b".claude/specs/2026-01-01-historical-design.md", 30, 4),
            self.row(b"src/app.py", 3, 1),
        ]
        result = self.scope(
            rows, (b".claude/specs/2026-08-16-diff-scope-helper-design.md",)
        )
        self.assertEqual(
            [row.path for row in result.files],
            [b".claude/specs/2026-01-01-historical-design.md", b"src/app.py"],
        )
        self.assertEqual(result.changed_lines, 38)
        self.assertEqual(result.excluded["artifact"], 1)

    def test_without_artifact_paths_a_historical_artifact_still_counts(self):
        rows = [
            self.row(b".claude/specs/2026-08-16-diff-scope-helper-design.md", 120, 0),
            self.row(b".claude/specs/2026-01-01-historical-design.md", 30, 4),
            self.row(b"src/app.py", 3, 1),
        ]
        result = self.scope(rows)
        self.assertEqual(result.changed_files, 3)
        self.assertEqual(result.changed_lines, 158)
        self.assertEqual(result.excluded["artifact"], 0)

    def test_artifact_prefix_matches_a_directory_not_a_sibling_prefix(self):
        rows = [
            self.row(b".claude/plans/run.md", 10, 0),
            self.row(b".claude/plans-archive/old.md", 7, 0),
        ]
        result = self.scope(rows, (b".claude/plans",))
        self.assertEqual(
            [row.path for row in result.files], [b".claude/plans-archive/old.md"]
        )
        self.assertEqual(result.excluded["artifact"], 1)

    # --- ranking, sums, and the zero cases --------------------------------

    def test_ranking_is_churn_descending_with_a_raw_byte_tie_break(self):
        rows = [
            self.row(b"b.txt", 5, 5),
            self.row(b"a.txt", 5, 5),
            self.row(b"c.txt", 9, 0),
        ]
        result = self.scope(rows)
        self.assertEqual(
            [row.path for row in result.files], [b"a.txt", b"b.txt", b"c.txt"]
        )
        self.assertEqual([row.churn for row in result.files], [10, 10, 9])

    def test_ranking_does_not_depend_on_input_order(self):
        forward = [
            self.row(b"a.txt", 5, 5),
            self.row(b"b.txt", 5, 5),
            self.row(b"c.txt", 9, 0),
        ]
        reverse = list(reversed(forward))
        self.assertEqual(
            [row.path for row in self.scope(forward).files],
            [row.path for row in self.scope(reverse).files],
        )

    def test_a_binary_row_is_one_product_file_and_zero_product_lines(self):
        result = self.scope(
            [self.row(b"assets/logo.png", None, None), self.row(b"src/app.py", 3, 1)]
        )
        self.assertEqual(result.changed_files, 2)
        self.assertEqual(result.changed_lines, 4)
        binary_row = next(
            row for row in result.files if row.path == b"assets/logo.png"
        )
        self.assertTrue(binary_row.binary)
        self.assertEqual(binary_row.churn, 0)

    def test_a_pure_rename_is_a_zero_churn_row_that_is_not_binary(self):
        result = self.scope([self.row(b"pkg/new.txt", 0, 0)])
        self.assertEqual(result.files[0].churn, 0)
        self.assertFalse(result.files[0].binary)
        self.assertEqual(result.changed_files, 1)

    def test_a_range_of_only_excluded_rows_measures_zero(self):
        rows = [
            self.row(b"pnpm-lock.yaml", 40, 2),
            self.row(b"api/types.ts", 90, 10, header=b"// Code generated by protoc.\n"),
            self.row(b".claude/plans/run.md", 200, 0),
        ]
        result = self.scope(rows, (b".claude/plans/run.md",))
        self.assertEqual(result.files, ())
        self.assertEqual(result.changed_lines, 0)
        self.assertEqual(result.changed_files, 0)
        self.assertEqual(
            result.excluded, {"lockfile": 1, "generated": 1, "artifact": 1}
        )

    def test_an_empty_row_set_measures_zero(self):
        result = self.scope([])
        self.assertEqual(result.files, ())
        self.assertEqual(result.changed_lines, 0)
        self.assertEqual(result.changed_files, 0)
        self.assertEqual(
            result.excluded, {"lockfile": 0, "generated": 0, "artifact": 0}
        )

    def test_each_row_is_counted_under_exactly_one_class(self):
        # A generated file under an artifact path counts once, as generated:
        # the order is lockfile -> generated -> artifact and the first match wins.
        rows = [
            self.row(b".claude/plans/gen.md", 10, 0, header=b"<auto-generated>\n"),
            self.row(b".claude/plans/Cargo.lock", 4, 4),
            self.row(b"src/app.py", 3, 1),
        ]
        result = self.scope(rows, (b".claude/plans",))
        self.assertEqual(
            result.excluded, {"lockfile": 1, "generated": 1, "artifact": 0}
        )
        self.assertEqual(
            len(result.files) + sum(result.excluded.values()), len(rows)
        )

    # --- output formats ---------------------------------------------------

    def test_json_output_is_compact_key_sorted_and_ascii(self):
        result = self.scope(
            [self.row(b"src/app.py", 3, 1), self.row(b"assets/logo.png", None, None)]
        )
        self.assertEqual(
            self.module.format_json("base..head", result),
            '{"excluded":{"artifact":0,"generated":0,"lockfile":0},'
            '"files":[{"binary":false,"changed_lines":4,"path":"src/app.py"},'
            '{"binary":true,"changed_lines":0,"path":"assets/logo.png"}],'
            '"product":{"changed_files":2,"changed_lines":4},'
            '"range":"base..head"}\n',
        )

    def test_a_non_utf8_path_survives_json_encoding(self):
        # APFS cannot hold such a name, so this hazard is only reachable here
        # and never from the CLI layer's scratch repositories (D19).
        result = self.scope([self.row(b"src/bad-\xff.py", 2, 0)])
        payload = self.module.format_json("base..head", result)
        self.assertEqual(payload, payload.encode("ascii").decode("ascii"))
        self.assertEqual(
            json.loads(payload)["files"][0]["path"], "src/bad-\udcff.py"
        )

    def test_text_output_names_the_totals_and_ranks_the_files(self):
        result = self.scope(
            [
                self.row(b"src/app.py", 3, 1),
                self.row(b"assets/logo.png", None, None),
                self.row(b"pnpm-lock.yaml", 40, 2),
            ]
        )
        self.assertEqual(
            self.module.format_text(result),
            "product: 4 lines, 2 files\n"
            "excluded: 1 lockfile, 0 generated, 0 artifact\n"
            "  4  src/app.py\n"
            "  0  assets/logo.png (binary)\n",
        )

    def test_a_newline_path_stays_on_one_text_line(self):
        # The text form is line-oriented, so a raw path byte must never end a
        # line: one ranked file is exactly one physical line, always.
        result = self.scope([self.row(b"we\nird.txt", 1, 0)])
        payload = self.module.format_text(result)
        self.assertEqual(
            payload,
            "product: 1 lines, 1 files\n"
            "excluded: 0 lockfile, 0 generated, 0 artifact\n"
            "  1  we\\nird.txt\n",
        )
        self.assertEqual(len(payload.splitlines()), 3)

    def test_every_control_byte_in_a_path_is_escaped_in_text_output(self):
        # Tab, carriage return and a bare C0 byte each get a backslash escape,
        # and a literal backslash is doubled so the escape stays unambiguous.
        result = self.scope([self.row(b"a\tb\rc\x01d\\e.txt", 1, 0)])
        self.assertEqual(
            self.module.format_text(result).splitlines()[2],
            "  1  a\\tb\\rc\\x01d\\\\e.txt",
        )

    def test_unicode_line_separators_in_a_path_are_escaped_in_text_output(self):
        # str.splitlines() breaks on ten characters; seven are C0 and already
        # escaped, and these three close the set (issue 31's D1). Four hex
        # digits keep the form disjoint from the two-digit \xNN escapes above.
        for character, escape in (
            ("\x85", "\\u0085"),
            ("\u2028", "\\u2028"),
            ("\u2029", "\\u2029"),
        ):
            with self.subTest(character=character):
                path = f"we{character}ird.txt".encode("utf-8")
                payload = self.module.format_text(self.scope([self.row(path, 1, 0)]))
                self.assertEqual(len(payload.splitlines()), 3)
                self.assertEqual(payload.splitlines()[2], f"  1  we{escape}ird.txt")

    def test_a_non_utf8_path_is_not_escaped_by_the_text_formatter(self):
        # Escaping is for line-breaking bytes only; an undecodable byte rides
        # through as its surrogate and is written back out verbatim by _emit.
        result = self.scope([self.row(b"src/bad-\xff.py", 2, 0)])
        self.assertEqual(
            self.module.format_text(result).splitlines()[2],
            "  2  src/bad-\udcff.py",
        )


GIT_LOCATION_VARS = (
    "GIT_DIR",
    "GIT_WORK_TREE",
    "GIT_INDEX_FILE",
    "GIT_OBJECT_DIRECTORY",
    "GIT_ALTERNATE_OBJECT_DIRECTORIES",
    "GIT_COMMON_DIR",
    "GIT_NAMESPACE",
)


def git_env():
    """A hermetic git environment: no user or system config, no signing.

    Every variable that relocates git's repository, work tree, index or object
    store is dropped, so an invoking session exporting one of them cannot
    redirect a scratch-repo command at an unrelated repository (issue 31's D7).
    The criterion is relocation, not the prefix: a blanket GIT_* sweep is
    rejected because it would also drop GIT_EXEC_PATH and GIT_TEMPLATE_DIR,
    which a Nix-provided git may rely on. The scrub pops from a copy of
    os.environ rather than building an allowlist, so PATH and HOME survive and
    both `git` and sys.executable keep resolving.
    """
    env = dict(os.environ)
    for name in GIT_LOCATION_VARS:
        env.pop(name, None)
    env.update(
        {
            "GIT_CONFIG_GLOBAL": "/dev/null",
            "GIT_CONFIG_SYSTEM": "/dev/null",
            "GIT_AUTHOR_NAME": "diff-scope-test",
            "GIT_AUTHOR_EMAIL": "diff-scope-test@example.invalid",
            "GIT_COMMITTER_NAME": "diff-scope-test",
            "GIT_COMMITTER_EMAIL": "diff-scope-test@example.invalid",
            "GIT_AUTHOR_DATE": "2026-01-01T00:00:00+00:00",
            "GIT_COMMITTER_DATE": "2026-01-01T00:00:00+00:00",
        }
    )
    return env


def git(root, *arguments):
    """Run one git command by argv, so a path argument never meets a shell."""
    completed = subprocess.run(
        ["git", *arguments],
        cwd=root,
        env=git_env(),
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise AssertionError(
            f"git {' '.join(arguments)} failed ({completed.returncode}): "
            f"{completed.stderr}"
        )
    return completed.stdout.strip()


def write(root, relative_path: bytes, content: bytes) -> None:
    """Write a file whose name may hold any byte APFS accepts (newline, quote)."""
    target = os.path.join(os.fsencode(root), relative_path)
    parent = os.path.dirname(target)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(target, "wb") as handle:
        handle.write(content)


def run_helper(root, *arguments):
    """Invoke the script the way a caller does, capturing raw bytes."""
    return subprocess.run(
        [sys.executable, str(SCRIPT), *arguments],
        cwd=root,
        env=git_env(),
        capture_output=True,
        check=False,
    )


def build_fixture_repo(root):
    """Two commits spanning every row shape the helper must survive."""
    git(root, "init", "-q", "-b", "main", ".")
    write(root, b"src/app.py", b"one\ntwo\nthree\n")
    write(root, b"pkg/old.txt", b"a\nb\nc\n")
    write(root, b"pnpm-lock.yaml", b"lock\n")
    write(root, b"assets/logo.png", b"\x00\x01\x02binary\x00")
    write(root, b"api/types.ts", b"// Code generated by protoc-gen-ts.\nexport {};\n")
    write(root, b"gone/Model.cs", b"// <auto-generated>\nclass Model {}\n")
    write(root, b"tie-a.txt", b"1\n2\n3\n4\n5\n")
    write(root, b"tie-b.txt", b"1\n2\n3\n4\n5\n")
    write(root, b".claude/specs/historical.md", b"old spec\n")
    git(root, "add", "-A")
    git(root, "commit", "-qm", "base")

    write(root, b"src/app.py", b"one\ntwo\nthree\nfour\n")
    git(root, "mv", "pkg/old.txt", "pkg/new.txt")
    write(root, b"pnpm-lock.yaml", b"lock\nmore\n")
    write(root, b"assets/logo.png", b"\x00\x01\x02BINARY CHANGED\x00\x00")
    write(
        root,
        b"api/types.ts",
        b"// Code generated by protoc-gen-ts.\nexport {};\nexport const x = 1;\n",
    )
    git(root, "rm", "-q", "gone/Model.cs")
    write(root, b"tie-a.txt", b"1\n2\n3\n4\n5\n6\n")
    write(root, b"tie-b.txt", b"1\n2\n3\n4\n5\n6\n")
    write(root, b".claude/specs/this-run.md", b"new spec\n")
    write(root, b"we\nird.txt", b"newline path\n")
    write(root, b'qu"ote.txt', b"quote path\n")
    write(root, "ls\u2028path.txt".encode("utf-8"), b"separator path\n")
    git(root, "add", "-A")
    git(root, "commit", "-qm", "head")


class DiffScopeCommandTest(unittest.TestCase):
    """The git layer and the CLI, against a real scratch repository.

    The fixture range HEAD~1..HEAD holds twelve rows: one lockfile, two
    generated (one of them a deletion, readable only on its base side), one
    binary, one pure rename, one spec artifact, and six ordinary product
    files -- two of which carry equal churn, and three of which carry a
    newline, a double quote and a U+2028 line separator in their names.
    """

    ARTIFACT = ".claude/specs/this-run.md"

    @classmethod
    def setUpClass(cls):
        cls.temporary = tempfile.TemporaryDirectory()
        cls.root = cls.temporary.name
        build_fixture_repo(cls.root)
        cls.range = "HEAD~1..HEAD"

    @classmethod
    def tearDownClass(cls):
        cls.temporary.cleanup()

    def measure(self, *arguments):
        completed = run_helper(self.root, self.range, *arguments)
        self.assertEqual(completed.returncode, 0, completed.stderr)
        return json.loads(completed.stdout.decode("utf-8"))

    def test_product_totals_exclude_every_class(self):
        payload = self.measure("--artifact-path", self.ARTIFACT)
        self.assertEqual(payload["range"], "HEAD~1..HEAD")
        self.assertEqual(payload["product"], {"changed_lines": 6, "changed_files": 8})
        self.assertEqual(
            payload["excluded"], {"lockfile": 1, "generated": 2, "artifact": 1}
        )

    def test_every_row_git_emitted_is_accounted_for_exactly_once(self):
        payload = self.measure("--artifact-path", self.ARTIFACT)
        raw = subprocess.run(
            ["git", "diff", "--numstat", "-z", "-M", self.range],
            cwd=self.root,
            env=git_env(),
            stdout=subprocess.PIPE,
            check=True,
        ).stdout
        # One count record per row; a rename adds two further path-only tokens.
        # No fixture path contains a tab, so a tab identifies a count record.
        rows = sum(1 for token in raw.split(b"\0") if token and b"\t" in token)
        self.assertEqual(rows, 12)
        self.assertEqual(
            len(payload["files"]) + sum(payload["excluded"].values()), rows
        )

    def test_a_path_shaped_revision_measures_the_same_as_its_object_id(self):
        # `:/subject` is a valid revision that is also path-shaped. Splicing it
        # raw into `<rev>:<path>` made every content read answer "missing", so
        # the range git accepted for the diff died on the content pass.
        expected = self.measure("--artifact-path", self.ARTIFACT)
        completed = run_helper(
            self.root, ":/base..:/head", "--artifact-path", self.ARTIFACT
        )
        self.assertEqual(completed.returncode, 0, completed.stderr)
        payload = json.loads(completed.stdout.decode("utf-8"))
        self.assertEqual(payload["product"], expected["product"])
        self.assertEqual(payload["excluded"], expected["excluded"])

    def test_a_deleted_generated_file_is_read_on_its_base_side(self):
        # gone/Model.cs exists only at base; head-side-only reading would miss
        # its <auto-generated> header and count it as product.
        payload = self.measure()
        self.assertNotIn(
            "gone/Model.cs", [entry["path"] for entry in payload["files"]]
        )
        self.assertEqual(payload["excluded"]["generated"], 2)

    def test_a_rename_is_one_zero_churn_row_under_its_new_path(self):
        entries = {entry["path"]: entry for entry in self.measure()["files"]}
        self.assertNotIn("pkg/old.txt", entries)
        self.assertEqual(
            entries["pkg/new.txt"],
            {"path": "pkg/new.txt", "changed_lines": 0, "binary": False},
        )

    def test_a_binary_row_is_product_with_zero_lines(self):
        entries = {entry["path"]: entry for entry in self.measure()["files"]}
        self.assertEqual(
            entries["assets/logo.png"],
            {"path": "assets/logo.png", "changed_lines": 0, "binary": True},
        )

    def test_paths_holding_a_newline_a_quote_or_a_separator_survive_end_to_end(self):
        paths = {entry["path"] for entry in self.measure()["files"]}
        self.assertIn("we\nird.txt", paths)
        self.assertIn('qu"ote.txt', paths)
        self.assertIn("ls\u2028path.txt", paths)

    def test_ties_rank_by_path(self):
        paths = [entry["path"] for entry in self.measure()["files"]]
        self.assertLess(paths.index("tie-a.txt"), paths.index("tie-b.txt"))

    def test_the_named_artifact_drops_and_counts_without_the_flag(self):
        with_flag = {
            entry["path"] for entry in self.measure("--artifact-path", self.ARTIFACT)["files"]
        }
        self.assertNotIn(self.ARTIFACT, with_flag)
        without_flag = {entry["path"] for entry in self.measure()["files"]}
        self.assertIn(self.ARTIFACT, without_flag)

    def test_an_artifact_path_matching_nothing_is_not_an_error(self):
        payload = self.measure("--artifact-path", ".claude/plans/never-written.md")
        self.assertEqual(payload["excluded"]["artifact"], 0)
        self.assertEqual(payload["product"]["changed_files"], 9)

    def test_a_leading_dot_slash_and_a_trailing_slash_are_stripped(self):
        payload = self.measure("--artifact-path", "./.claude/specs/")
        self.assertEqual(payload["excluded"]["artifact"], 1)

    def test_output_is_byte_identical_across_two_runs(self):
        first = run_helper(self.root, self.range, "--artifact-path", self.ARTIFACT)
        second = run_helper(self.root, self.range, "--artifact-path", self.ARTIFACT)
        self.assertEqual(first.returncode, 0, first.stderr)
        self.assertEqual(first.stdout, second.stdout)

    def test_the_suite_git_environment_is_immune_to_an_inherited_git_dir(self):
        # An invoking session exporting GIT_DIR redirects every scratch-repo git
        # call and every helper subprocess at an unrelated repository (issue
        # 31's D7).
        poison = {
            "GIT_DIR": "/nonexistent/other.git",
            "GIT_WORK_TREE": "/nonexistent/tree",
            "GIT_INDEX_FILE": "/nonexistent/index",
        }
        baseline = self.measure("--artifact-path", self.ARTIFACT)
        with unittest.mock.patch.dict(os.environ, poison):
            env = git_env()
            for name in poison:
                self.assertNotIn(name, env)
            completed = run_helper(
                self.root, self.range, "--artifact-path", self.ARTIFACT
            )
        self.assertEqual(completed.returncode, 0, completed.stderr)
        self.assertEqual(json.loads(completed.stdout.decode("utf-8")), baseline)

    def test_text_format_reports_the_same_totals(self):
        completed = run_helper(
            self.root, self.range, "--format", "text", "--artifact-path", self.ARTIFACT
        )
        self.assertEqual(completed.returncode, 0, completed.stderr)
        lines = completed.stdout.decode("utf-8").splitlines()
        self.assertEqual(lines[0], "product: 6 lines, 8 files")
        self.assertEqual(lines[1], "excluded: 1 lockfile, 2 generated, 1 artifact")
        self.assertIn("  0  assets/logo.png (binary)", lines)

    def test_text_format_gives_each_ranked_file_exactly_one_line(self):
        completed = run_helper(
            self.root, self.range, "--format", "text", "--artifact-path", self.ARTIFACT
        )
        self.assertEqual(completed.returncode, 0, completed.stderr)
        text = completed.stdout.decode("utf-8")
        # we\nird.txt adds one line and deletes none, so its churn is 1.
        self.assertIn("  1  we\\nird.txt\n", text)
        # The separator path is one added line, and one physical line.
        self.assertIn("  1  ls\\u2028path.txt\n", text)
        # Two header lines plus one line per product file (8), and nothing else:
        # an unescaped newline or U+2028 path splits one of them.
        self.assertEqual(len(text.splitlines()), 2 + 8)

    def test_an_empty_range_measures_zero_and_succeeds(self):
        completed = run_helper(self.root, "HEAD..HEAD")
        self.assertEqual(completed.returncode, 0, completed.stderr)
        payload = json.loads(completed.stdout.decode("utf-8"))
        self.assertEqual(payload["product"], {"changed_lines": 0, "changed_files": 0})
        self.assertEqual(payload["files"], [])
        self.assertEqual(
            payload["excluded"], {"lockfile": 0, "generated": 0, "artifact": 0}
        )

    def test_a_malformed_range_exits_one(self):
        for bad in ("HEAD", "HEAD...HEAD~1", "..HEAD", "HEAD..", "a..b..c"):
            with self.subTest(range=bad):
                completed = run_helper(self.root, bad)
                self.assertEqual(completed.returncode, 1, completed.stdout)
                self.assertIn(b"diff-scope:", completed.stderr)

    def test_an_unknown_revision_exits_one(self):
        completed = run_helper(self.root, "HEAD..no-such-revision")
        self.assertEqual(completed.returncode, 1, completed.stdout)
        self.assertIn(b"diff-scope:", completed.stderr)

    def test_a_root_outside_a_work_tree_exits_one(self):
        with tempfile.TemporaryDirectory() as outside:
            completed = subprocess.run(
                [sys.executable, str(SCRIPT), self.range, "--root", outside],
                env=git_env(),
                capture_output=True,
                check=False,
            )
        self.assertEqual(completed.returncode, 1, completed.stdout)
        self.assertIn(b"work tree", completed.stderr)

    def test_an_absolute_or_escaping_artifact_path_exits_one(self):
        for bad in ("/etc/passwd", "../outside.md", "a/../../b.md"):
            with self.subTest(value=bad):
                completed = run_helper(self.root, self.range, "--artifact-path", bad)
                self.assertEqual(completed.returncode, 1, completed.stdout)
                self.assertIn(b"diff-scope:", completed.stderr)


if __name__ == "__main__":
    unittest.main()
