"""Contract tests for scripts/resolve-project.

Runs the resolver as a subprocess against temporary repository roots and parses
its stdout, the seam established by test_resolve_bindings.py and
test_workflow_state.py. The resolver is imported only by the two cases whose
seam no subprocess run can reach — the generic failure wrapper and the
emit-side non-finite guard — through the shared `load_module` below.
"""

from __future__ import annotations

import contextlib
import copy
import io
import json
import os
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "resolve-project.py"
REPO_ROOT = Path(__file__).resolve().parents[4]

CAPABILITY_NAMES = (
    "tracker", "worktrees", "knowledge.context", "knowledge.standards",
    "knowledge.architecture", "knowledge.hints", "verification",
    "review.plan", "review.code", "release", "deploy",
)
BINDING_NAMESPACES = ("vcs", "tracker", "paths", "commands", "workflow", "deploy")
CAPABILITY_STATES = ("available", "unsupported", "blocked")


def run(*args: str) -> tuple[int, str, str]:
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True, text=True, timeout=60,
    )
    return proc.returncode, proc.stdout, proc.stderr


def git(root: Path, *args: str) -> str:
    """Run git in `root` with a hermetic identity and return its stdout."""
    proc = subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True, text=True, timeout=60, check=True,
        env=dict(
            os.environ,
            GIT_CONFIG_GLOBAL=os.devnull,
            GIT_CONFIG_SYSTEM=os.devnull,
            GIT_AUTHOR_NAME="t", GIT_AUTHOR_EMAIL="t@example.invalid",
            GIT_COMMITTER_NAME="t", GIT_COMMITTER_EMAIL="t@example.invalid",
        ),
    )
    return proc.stdout


def tree_snapshot(root: Path) -> list[tuple[str, str, int | None]]:
    """Every path under `root` outside `.git`, with its type and file mtime.

    Directories are included so that creating an empty one is caught; `.git`
    is excluded because git's own bookkeeping is not the resolver's writing.
    """
    out = []
    for path in sorted(root.rglob("*")):
        if ".git" in path.relative_to(root).parts:
            continue
        kind = "d" if path.is_dir() else "f"
        out.append((
            str(path.relative_to(root)), kind,
            None if kind == "d" else path.stat().st_mtime_ns,
        ))
    return out


def assert_read_only(case: unittest.TestCase, root: Path,
                     expected_code: int, *args: str) -> None:
    """Assert the resolver invocation `args` writes nothing under `root`.

    Three independent witnesses, because each misses what the others catch:
    `git status --porcelain` bytes catch a tracked-content or index change, the
    recursive path/type set catches a created empty directory, and the file
    mtimes catch a rewrite with identical bytes (SF-001, AC-5).
    """
    git(root, "add", "-A")
    git(root, "commit", "--quiet", "-m", "fixture")
    before_status = git(root, "status", "--porcelain")
    before_tree = tree_snapshot(root)
    code, _, err = run(*args, "--repo-root", str(root))
    case.assertEqual(code, expected_code, err)
    case.assertEqual(git(root, "status", "--porcelain"), before_status)
    case.assertEqual(tree_snapshot(root), before_tree)


def source_contract() -> dict:
    return json.loads((REPO_ROOT / ".agents" / "project.json").read_text("utf-8"))


CODEX_HEADER = (
    "<!-- generated by resolve-project from .agents/instructions/bootstrap.md "
    "(project schema 1). Do not edit; edit the source and run "
    "`resolve-project write-projections`. -->"
)
MANAGED_LINE = "@.agents/instructions/bootstrap.md"


class ResolverTestCase(unittest.TestCase):
    def make_root(self, contract: object | None = None, *,
                  projections: bool = True) -> Path:
        """A temp root holding a valid contract, its instruction source, and —
        unless `projections=False` — both projection targets rendered current.

        `resolve` refuses a drifted projection before it reaches anything else
        (D10), so a root without current targets would refuse for a reason no
        caller here means to exercise. Only the cases that must start from an
        unwritten state opt out.
        """
        # `.resolve()` because the platform temp dir is reached through a
        # symlink on macOS (/var -> /private/var) while the resolver's own
        # root is always the physical path; without it every `str(root)`
        # comparison below would compare two spellings of one directory.
        root = Path(tempfile.mkdtemp()).resolve()
        git(root, "init", "--quiet")
        (root / "home" / "common" / "agent-skills" / "standards").mkdir(parents=True)
        (root / ".out-of-scope").mkdir()
        (root / ".worktrees").mkdir()
        (root / ".agents" / "instructions").mkdir(parents=True)
        (root / ".agents" / "instructions" / "bootstrap.md").write_text(
            "# invariants\n", encoding="utf-8")
        if contract is None:
            contract = source_contract()
        if contract is not False:
            (root / ".agents" / "project.json").write_text(
                json.dumps(contract), encoding="utf-8")
        body = "# authored body\n"
        if projections:
            source = (root / ".agents" / "instructions" / "bootstrap.md").read_bytes()
            (root / "AGENTS.md").write_bytes(
                CODEX_HEADER.encode() + b"\n\n" + source)
            body += MANAGED_LINE + "\n"
        (root / "CLAUDE.md").write_text(body, encoding="utf-8")
        return root

    def resolve(self, root: Path, *extra: str) -> tuple[int, object, str]:
        code, out, err = run("resolve", "--repo-root", str(root), *extra)
        try:
            payload: object = json.loads(out)
        except json.JSONDecodeError:
            payload = None
        return code, payload, err


class SnapshotShapeTest(ResolverTestCase):
    def test_resolve_returns_exactly_four_top_level_members(self):
        code, snap, err = self.resolve(self.make_root())
        self.assertEqual(code, 0, err)
        self.assertEqual(
            sorted(snap), ["bindings", "capabilities", "project", "schema_version"])
        self.assertEqual(snap["schema_version"], 1)
        self.assertEqual(sorted(snap["project"]), ["id", "name", "root"])
        self.assertEqual(sorted(snap["bindings"]), sorted(BINDING_NAMESPACES))
        self.assertEqual(sorted(snap["capabilities"]), sorted(CAPABILITY_NAMES))
        for name, entry in snap["capabilities"].items():
            with self.subTest(capability=name):
                self.assertEqual(sorted(entry), ["reason_code", "repair_id", "state"])
                self.assertIn(entry["state"], CAPABILITY_STATES)

    def test_identity_is_copied_verbatim_from_the_source(self):
        root = self.make_root()
        code, snap, err = self.resolve(root)
        self.assertEqual(code, 0, err)
        self.assertEqual(snap["project"]["id"], "fagenorn/nix-config")
        self.assertEqual(snap["project"]["name"], "nix-config")
        self.assertEqual(snap["project"]["root"], str(root.resolve()))

    def test_unsupported_capabilities_carry_null_reason_and_repair(self):
        code, snap, err = self.resolve(self.make_root())
        self.assertEqual(code, 0, err)
        for name in ("release", "deploy", "knowledge.context", "knowledge.hints"):
            with self.subTest(capability=name):
                entry = snap["capabilities"][name]
                self.assertEqual(entry["state"], "unsupported")
                self.assertIsNone(entry["reason_code"])
                self.assertIsNone(entry["repair_id"])

    def test_two_runs_emit_byte_identical_stdout(self):
        root = self.make_root()
        first = run("resolve", "--repo-root", str(root))
        second = run("resolve", "--repo-root", str(root))
        self.assertEqual(first[0], 0, first[2])
        self.assertEqual(first[1], second[1])

    def test_stdout_is_compact_sorted_json_with_a_trailing_newline(self):
        code, out, err = run("resolve", "--repo-root", str(self.make_root()))
        self.assertEqual(code, 0, err)
        self.assertTrue(out.endswith("\n"))
        self.assertNotIn("\n", out[:-1])
        self.assertEqual(out, json.dumps(
            json.loads(out), sort_keys=True, separators=(",", ":")) + "\n")


class NormalizationTest(ResolverTestCase):
    def test_every_path_is_absolute_under_project_root(self):
        root = self.make_root()
        code, snap, err = self.resolve(root)
        self.assertEqual(code, 0, err)
        paths = snap["bindings"]["paths"]
        candidates = [paths["artifacts"]["specs"], paths["artifacts"]["plans"]]
        for key in ("context", "standards", "architecture", "operations",
                    "hints", "rejections"):
            candidates.extend(paths[key])
        candidates.extend(c["cwd"] for c in snap["bindings"]["commands"].values())
        for value in candidates:
            with self.subTest(path=value):
                self.assertTrue(Path(value).is_absolute())
                self.assertTrue(
                    value == str(root.resolve())
                    or value.startswith(str(root.resolve()) + "/"))

    def test_the_source_file_keeps_its_relative_values(self):
        root = self.make_root()
        self.assertEqual(self.resolve(root)[0], 0)
        on_disk = json.loads((root / ".agents" / "project.json").read_text("utf-8"))
        self.assertEqual(
            on_disk["bindings"]["paths"]["artifacts"]["plans"], ".claude/plans")

    def test_non_path_binding_values_pass_through_unchanged(self):
        root = self.make_root()
        code, snap, err = self.resolve(root)
        self.assertEqual(code, 0, err)
        source = json.loads((root / ".agents" / "project.json").read_text("utf-8"))
        self.assertEqual(snap["bindings"]["vcs"], source["bindings"]["vcs"])
        self.assertEqual(snap["bindings"]["tracker"], source["bindings"]["tracker"])
        self.assertEqual(snap["bindings"]["workflow"], source["bindings"]["workflow"])


class ReadOnlyTest(ResolverTestCase):
    """AC-5: running the resolver leaves the working tree unchanged (SF-001)."""

    def test_resolve_leaves_the_tree_untouched(self):
        assert_read_only(self, self.make_root(), 0, "resolve")

    def test_a_refusing_resolve_leaves_the_tree_untouched(self):
        root = self.make_root()
        (root / ".agents" / "project.json").write_text("{", encoding="utf-8")
        assert_read_only(self, root, 2, "resolve")


class ErrorOutputTest(ResolverTestCase):
    def assert_refusal(self, code: int, payload: object, expected: str) -> dict:
        self.assertEqual(code, 2)
        self.assertIsInstance(payload, dict)
        self.assertEqual(sorted(payload), ["error"])
        self.assertNotIn("schema_version", payload)
        error = payload["error"]
        self.assertEqual(sorted(error), ["code", "repair_id", "violations"])
        self.assertEqual(error["code"], expected)
        self.assertTrue(error["violations"])
        pointers = [v["pointer"] for v in error["violations"]]
        self.assertEqual(pointers, sorted(pointers))
        for violation in error["violations"]:
            self.assertEqual(sorted(violation), ["message", "pointer"])
        return error

    def test_missing_contract_is_not_onboarded(self):
        root = self.make_root(contract=False)
        code, payload, _ = self.resolve(root)
        error = self.assert_refusal(code, payload, "not_onboarded")
        self.assertEqual(error["repair_id"], "onboarding.contract.missing")

    def test_repo_root_does_not_walk_up(self):
        root = self.make_root()
        nested = root / "sub" / "deeper"
        nested.mkdir(parents=True)
        code, payload, _ = self.resolve(nested)
        self.assert_refusal(code, payload, "not_onboarded")

    def test_non_json_contract_is_invalid_contract(self):
        root = self.make_root()
        (root / ".agents" / "project.json").write_text("{not json", encoding="utf-8")
        code, payload, _ = self.resolve(root)
        error = self.assert_refusal(code, payload, "invalid_contract")
        self.assertEqual(error["repair_id"], "contract.parse")

    def test_a_non_finite_number_is_invalid_contract(self):
        """COR-001: Python's decoder accepts bare `NaN`; the contract does not.

        `bindings.deploy.config` is an unconstrained dict, so no later shape
        rule would have stopped the token: it would reach the snapshot and be
        re-emitted as JSON no standards parser can read. The refusal is the
        closed `invalid_contract`, not `resolver_failure`.
        """
        expected = (".agents/project.json holds NaN, Infinity or -Infinity, "
                    "which JSON has no value for")
        for token, value in (("NaN", float("nan")),
                             ("Infinity", float("inf")),
                             ("-Infinity", float("-inf"))):
            with self.subTest(token=token):
                contract = source_contract()
                contract["bindings"]["deploy"]["config"] = {"threshold": value}
                root = self.make_root(contract)
                # The fixture writes the contract with `json.dumps`, which
                # emits the bare token: assert the input really carries it.
                self.assertIn(
                    f": {token}}}",
                    (root / ".agents" / "project.json").read_text("utf-8"))
                code, payload, _ = self.resolve(root)
                error = self.assert_refusal(code, payload, "invalid_contract")
                self.assertEqual(error["repair_id"], "contract.parse")
                self.assertEqual(
                    [v["message"] for v in error["violations"]], [expected])

    def test_non_object_contract_is_invalid_contract(self):
        root = self.make_root(contract=[1, 2, 3])
        error = self.assert_refusal(*self.resolve(root)[:2], "invalid_contract")
        self.assertEqual(error["repair_id"], "contract.parse")

    def test_missing_schema_version_is_invalid_contract(self):
        contract = source_contract()
        del contract["schema_version"]
        code, payload, _ = self.resolve(self.make_root(contract))
        error = self.assert_refusal(code, payload, "invalid_contract")
        self.assertEqual(error["repair_id"], "contract.schema_version.invalid")

    def test_boolean_schema_version_is_invalid_contract(self):
        contract = source_contract()
        contract["schema_version"] = True
        code, payload, _ = self.resolve(self.make_root(contract))
        error = self.assert_refusal(code, payload, "invalid_contract")
        self.assertEqual(error["repair_id"], "contract.schema_version.invalid")

    def test_other_integer_schema_version_is_unsupported_schema(self):
        contract = source_contract()
        contract["schema_version"] = 2
        code, payload, _ = self.resolve(self.make_root(contract))
        error = self.assert_refusal(code, payload, "unsupported_schema")
        self.assertEqual(error["repair_id"], "contract.schema_version.unsupported")

    def test_an_unknown_top_level_member_is_refused(self):
        contract = source_contract()
        contract["extra"] = {}
        code, payload, _ = self.resolve(self.make_root(contract))
        self.assert_refusal(code, payload, "invalid_contract")

    def test_all_violations_are_reported_in_one_pass(self):
        contract = source_contract()
        del contract["bindings"]["deploy"]
        del contract["capabilities"]["release"]
        code, payload, _ = self.resolve(self.make_root(contract))
        error = self.assert_refusal(code, payload, "invalid_contract")
        pointers = [v["pointer"] for v in error["violations"]]
        self.assertIn("/bindings/deploy", pointers)
        self.assertIn("/capabilities/release", pointers)


class NoDefaultingTest(ResolverTestCase):
    def test_dropping_any_binding_namespace_refuses(self):
        for namespace in BINDING_NAMESPACES:
            with self.subTest(namespace=namespace):
                contract = source_contract()
                del contract["bindings"][namespace]
                code, payload, _ = self.resolve(self.make_root(contract))
                self.assertEqual(code, 2)
                self.assertEqual(payload["error"]["code"], "invalid_contract")
                self.assertIn(f"/bindings/{namespace}",
                              [v["pointer"] for v in payload["error"]["violations"]])

    def test_dropping_any_capability_declaration_refuses(self):
        for name in CAPABILITY_NAMES:
            with self.subTest(capability=name):
                contract = source_contract()
                del contract["capabilities"][name]
                code, payload, _ = self.resolve(self.make_root(contract))
                self.assertEqual(code, 2)
                self.assertEqual(payload["error"]["code"], "invalid_contract")

    def test_a_dangling_command_id_refuses(self):
        contract = source_contract()
        contract["bindings"]["workflow"]["verification"] = ["no-such-command"]
        code, payload, _ = self.resolve(self.make_root(contract))
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "invalid_contract")

    def test_unsafe_authored_paths_refuse(self):
        for value in ("/etc", "../escape", "a/../../b"):
            with self.subTest(path=value):
                contract = source_contract()
                contract["bindings"]["paths"]["artifacts"]["plans"] = value
                code, payload, _ = self.resolve(self.make_root(contract))
                self.assertEqual(code, 2)
                self.assertEqual(payload["error"]["code"], "invalid_contract")

    def test_a_refusal_emits_no_snapshot_member(self):
        contract = source_contract()
        del contract["bindings"]["vcs"]
        code, out, _ = run("resolve", "--repo-root", str(self.make_root(contract)))
        self.assertEqual(code, 2)
        for member in ("schema_version", "project", "bindings", "capabilities"):
            self.assertNotIn(f'"{member}"', out)


class MalformedValueTest(ResolverTestCase):
    """B-003: a wrongly typed or empty leaf is a violation, never a snapshot."""

    CASES = (
        ("/bindings/vcs/default_branch", ("bindings", "vcs", "default_branch"), None),
        ("/bindings/vcs/branch_pattern", ("bindings", "vcs", "branch_pattern"), ""),
        ("/bindings/vcs/kind", ("bindings", "vcs", "kind"), 1),
        ("/bindings/vcs/commit/signed", ("bindings", "vcs", "commit", "signed"), 1),
        ("/bindings/tracker/repo_slug", ("bindings", "tracker", "repo_slug"), []),
        ("/bindings/tracker/cli", ("bindings", "tracker", "cli"), ""),
        ("/bindings/deploy/adapter", ("bindings", "deploy", "adapter"), None),
    )

    def test_each_malformed_leaf_is_an_invalid_contract_violation(self):
        for pointer, path, bad in self.CASES:
            with self.subTest(pointer=pointer):
                source = source_contract()
                target = source
                for key in path[:-1]:
                    target = target[key]
                target[path[-1]] = bad
                root = self.make_root(source)
                code, payload, _ = self.resolve(root)
                self.assertEqual(code, 2)
                self.assertEqual(payload["error"]["code"], "invalid_contract")
                self.assertIn(pointer,
                              [v["pointer"] for v in payload["error"]["violations"]])
                self.assertNotIn("schema_version", payload)


class CommandArgvTest(ResolverTestCase):
    """COR-002: every `argv` word is a non-empty string, at its own pointer.

    An empty `argv` list is already refused, and an empty word is the same
    break one level down: `[""]` names no executable, and an empty later word
    is an argument the callee cannot have meant.
    """

    CASES = (
        ("an empty executable", ["", "build"], 0),
        ("an empty later argument", ["just", ""], 1),
    )

    def test_an_empty_argv_word_is_an_invalid_contract_violation(self):
        for label, argv, index in self.CASES:
            with self.subTest(case=label):
                contract = source_contract()
                contract["bindings"]["commands"]["nix-build"]["argv"] = argv
                code, payload, _ = self.resolve(self.make_root(contract))
                self.assertEqual(code, 2)
                self.assertEqual(payload["error"]["code"], "invalid_contract")
                self.assertIn(
                    f"/bindings/commands/nix-build/argv/{index}",
                    [v["pointer"] for v in payload["error"]["violations"]])

    def test_an_unreferenced_commands_entry_is_validated_too(self):
        """Validation walks every entry, not only the ids workflow names."""
        contract = source_contract()
        contract["bindings"]["commands"]["orphan"] = {
            "argv": [""], "cwd": ".", "env": []}
        code, payload, _ = self.resolve(self.make_root(contract))
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "invalid_contract")
        self.assertIn("/bindings/commands/orphan/argv/0",
                      [v["pointer"] for v in payload["error"]["violations"]])

    def test_a_non_string_argv_word_is_still_refused(self):
        contract = source_contract()
        contract["bindings"]["commands"]["nix-build"]["argv"] = ["just", 7]
        code, payload, _ = self.resolve(self.make_root(contract))
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "invalid_contract")
        self.assertIn("/bindings/commands/nix-build/argv/1",
                      [v["pointer"] for v in payload["error"]["violations"]])


class OnePassCollectionTest(ResolverTestCase):
    """B-004: `invalid_contract` reports every violation, `schema_version` included."""

    def test_an_invalid_schema_version_is_collected_with_the_others(self):
        source = source_contract()
        source["schema_version"] = "1"
        del source["bindings"]["deploy"]
        root = self.make_root(source)
        code, payload, _ = self.resolve(root)
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "invalid_contract")
        pointers = [v["pointer"] for v in payload["error"]["violations"]]
        self.assertIn("/schema_version", pointers)
        self.assertIn("/bindings/deploy", pointers)
        self.assertEqual(pointers, sorted(pointers))

    def test_an_unsupported_integer_version_short_circuits(self):
        source = source_contract()
        source["schema_version"] = 2
        del source["bindings"]["deploy"]
        root = self.make_root(source)
        code, payload, _ = self.resolve(root)
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "unsupported_schema")
        self.assertEqual(
            [v["pointer"] for v in payload["error"]["violations"]],
            ["/schema_version"])


class DiscoveryTest(ResolverTestCase):
    """SF-002: the nearest-ancestor walk taken without `--repo-root`."""

    def resolve_from(self, cwd: Path) -> tuple[int, object, str]:
        proc = subprocess.run(
            [sys.executable, str(SCRIPT), "resolve"],
            capture_output=True, text=True, timeout=60, cwd=str(cwd))
        try:
            payload: object = json.loads(proc.stdout)
        except json.JSONDecodeError:
            payload = None
        return proc.returncode, payload, proc.stderr

    def test_a_nested_directory_finds_the_nearest_ancestor(self):
        root = self.make_root()
        nested = root / "home" / "common" / "agent-skills" / "standards"
        code, snap, err = self.resolve_from(nested)
        self.assertEqual(code, 0, err)
        self.assertEqual(snap["project"]["root"], str(root))

    def test_no_contract_above_the_start_directory_is_not_onboarded(self):
        bare = Path(tempfile.mkdtemp())
        code, payload, _ = self.resolve_from(bare)
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "not_onboarded")


class UsageErrorTest(ResolverTestCase):
    """SF-002: a missing subcommand is argparse's error, not JSON.

    `write-projections` left this list when Task 3 registered it, and
    `check-projections` when this task did (D18): every subcommand the
    resolver names is now implemented, so only the empty argv remains. A
    registered subcommand cannot stand in for one, because this case passes
    no `--repo-root` and would walk up from the runner's own directory onto
    the live checkout.
    """

    def test_an_unregistered_subcommand_exits_two_without_json(self):
        for args in ((),):
            with self.subTest(args=args):
                code, out, err = run(*args)
                self.assertEqual(code, 2)
                self.assertEqual(out, "")
                self.assertNotEqual(err, "")


def load_module():
    """The resolver as an imported module, loaded by path (its name is hyphenated).

    Reserved for the seams no subprocess run can reach: the generic failure
    wrapper, and the emit-side guard that the parse-side guard keeps unreachable
    from any authored contract.
    """
    import importlib.util
    spec = importlib.util.spec_from_file_location("resolve_project", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ResolverFailureTest(unittest.TestCase):
    """SF-002: the generic handler maps an unexpected exception to the closed code.

    No external input reaches this branch deterministically — every I/O and
    shape failure is already classified — so the seam is the wrapper itself.
    """

    def test_an_unexpected_exception_becomes_resolver_failure(self):
        module = load_module()
        original = module.load_contract
        # A sentinel no fixed refusal sentence can contain: the prescribed
        # message is "the resolver failed unexpectedly", so a shorter probe
        # like "unexpected" would match the message rather than the leak.
        module.load_contract = lambda root: (_ for _ in ()).throw(
            RuntimeError("sentinel-exception-detail"))
        buffer = io.StringIO()
        try:
            with contextlib.redirect_stdout(buffer):
                code = module.main(["resolve", "--repo-root", str(REPO_ROOT)])
        finally:
            module.load_contract = original
        self.assertEqual(code, 2)
        payload = json.loads(buffer.getvalue())
        self.assertEqual(payload["error"]["code"], "resolver_failure")
        self.assertEqual(payload["error"]["repair_id"], "resolver.internal")
        self.assertNotIn("schema_version", payload)
        self.assertNotIn("sentinel-exception-detail", json.dumps(payload),
                         "the internal message must not leak the exception text")


class EmitGuardTest(unittest.TestCase):
    """COR-001: the writing side refuses a non-finite float on its own.

    The parse-side guard keeps this unreachable from any authored contract,
    which is the point — it is the second half of the check, not a duplicate
    of the first: `emit_json` never prints a token another JSON parser would
    reject, whatever put the value in front of it.
    """

    def test_emitting_a_non_finite_float_raises(self):
        module = load_module()
        for value in (float("nan"), float("inf"), float("-inf")):
            with self.subTest(value=repr(value)):
                buffer = io.StringIO()
                with self.assertRaises(ValueError):
                    with contextlib.redirect_stdout(buffer):
                        module.emit_json({"deploy": {"config": value}})
                self.assertNotIn("NaN", buffer.getvalue())
                self.assertNotIn("Infinity", buffer.getvalue())

    def test_emitting_finite_values_is_unchanged(self):
        module = load_module()
        buffer = io.StringIO()
        with contextlib.redirect_stdout(buffer):
            module.emit_json({"b": 1, "a": [2.5, "x"]})
        self.assertEqual(buffer.getvalue(), '{"a":[2.5,"x"],"b":1}\n')


class CommittedContractTest(ResolverTestCase):
    def test_the_repositorys_own_contract_is_structurally_valid(self):
        contract = source_contract()
        self.assertEqual(contract["schema_version"], 1)
        self.assertEqual(sorted(contract["capabilities"]), sorted(CAPABILITY_NAMES))
        self.assertEqual(sorted(contract["bindings"]), sorted(BINDING_NAMESPACES))

    def test_orchestration_values_match_the_legacy_config(self):
        legacy = json.loads(
            (REPO_ROOT / ".claude" / "skills.config.json").read_text("utf-8"))
        orchestration = source_contract()["bindings"]["workflow"]["orchestration"]
        self.assertEqual(orchestration["max_parallel"],
                         legacy["orchestration"]["maxParallel"])
        self.assertEqual(orchestration["attempt_budget_minutes"],
                         legacy["orchestration"]["agentBudgetMinutes"])


def run_with_path(path_value: str, *args: str) -> tuple[int, str, str]:
    """Run the resolver with `PATH` replaced by exactly `path_value`.

    The interpreter is `sys.executable`, an absolute path, because `PATH` here
    holds only the stub directory and no Python (B-002).
    """
    env = dict(os.environ, PATH=path_value)
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True, text=True, timeout=60, env=env,
    )
    return proc.returncode, proc.stdout, proc.stderr


def make_stub_bin(names: tuple[str, ...]) -> Path:
    """A directory holding executable no-op stubs for the named binaries."""
    stub = Path(tempfile.mkdtemp())
    for name in names:
        target = stub / name
        target.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        target.chmod(target.stat().st_mode | stat.S_IXUSR)
    return stub


class CapabilityStateTest(ResolverTestCase):
    def resolve_with_path(self, root: Path, stub: Path, *extra: str):
        code, out, err = run_with_path(
            str(stub), "resolve", "--repo-root", str(root), *extra)
        try:
            payload: object = json.loads(out)
        except json.JSONDecodeError:
            payload = None
        return code, payload, out, err

    def test_available_when_every_prerequisite_is_present(self):
        root = self.make_root()
        stub = make_stub_bin(("gh", "git", "just", "codex"))
        code, snap, _, err = self.resolve_with_path(root, stub)
        self.assertEqual(code, 0, err)
        for name in ("tracker", "worktrees", "knowledge.standards",
                     "knowledge.architecture", "verification",
                     "review.plan", "review.code"):
            with self.subTest(capability=name):
                entry = snap["capabilities"][name]
                self.assertEqual(entry["state"], "available")
                self.assertIsNone(entry["reason_code"])
                self.assertIsNone(entry["repair_id"])

    def test_tracker_is_blocked_when_its_cli_is_absent(self):
        root = self.make_root()
        stub = make_stub_bin(("git", "just", "codex"))
        code, snap, _, err = self.resolve_with_path(root, stub)
        self.assertEqual(code, 0, err)
        entry = snap["capabilities"]["tracker"]
        self.assertEqual(entry["state"], "blocked")
        self.assertEqual(entry["reason_code"], "tracker_cli_missing")
        self.assertEqual(entry["repair_id"], "capability.tracker.tracker_cli_missing")

    def test_worktrees_is_blocked_when_git_is_absent(self):
        root = self.make_root()
        stub = make_stub_bin(("gh", "just", "codex"))
        code, snap, _, err = self.resolve_with_path(root, stub)
        self.assertEqual(code, 0, err)
        entry = snap["capabilities"]["worktrees"]
        self.assertEqual(entry["state"], "blocked")
        self.assertEqual(entry["reason_code"], "vcs_worktree_unsupported")
        self.assertEqual(entry["repair_id"],
                         "capability.worktrees.vcs_worktree_unsupported")

    def test_verification_is_blocked_when_a_command_binary_is_absent(self):
        root = self.make_root()
        stub = make_stub_bin(("gh", "git", "codex"))
        code, snap, _, err = self.resolve_with_path(root, stub)
        self.assertEqual(code, 0, err)
        entry = snap["capabilities"]["verification"]
        self.assertEqual(entry["state"], "blocked")
        self.assertEqual(entry["reason_code"], "command_missing")
        self.assertEqual(entry["repair_id"], "capability.verification.command_missing")

    def test_knowledge_is_blocked_when_a_declared_path_is_absent(self):
        # The absent path is declared rather than deleted: `CLAUDE.md` is a
        # projection target, and removing it would refuse as drift (D10)
        # before any readiness is computed.
        contract = source_contract()
        contract["bindings"]["paths"]["architecture"] = ["docs/architecture.md"]
        root = self.make_root(contract)
        stub = make_stub_bin(("gh", "git", "just", "codex"))
        code, snap, _, err = self.resolve_with_path(root, stub)
        self.assertEqual(code, 0, err)
        entry = snap["capabilities"]["knowledge.architecture"]
        self.assertEqual(entry["state"], "blocked")
        self.assertEqual(entry["reason_code"], "knowledge_path_missing")
        self.assertEqual(entry["repair_id"],
                         "capability.knowledge.architecture.knowledge_path_missing")

    def test_every_blocked_reason_code_is_from_the_closed_set(self):
        root = self.make_root()
        code, snap, _, err = self.resolve_with_path(root, make_stub_bin(()))
        self.assertEqual(code, 0, err)
        for name, entry in snap["capabilities"].items():
            with self.subTest(capability=name):
                if entry["state"] == "blocked":
                    self.assertIn(entry["reason_code"],
                                  ("tracker_cli_missing", "vcs_worktree_unsupported",
                                   "knowledge_path_missing", "command_missing"))
                    self.assertEqual(entry["repair_id"],
                                     f"capability.{name}.{entry['reason_code']}")
                else:
                    self.assertIsNone(entry["reason_code"])
                    self.assertIsNone(entry["repair_id"])

    def test_unsupported_capabilities_never_evaluate_prerequisites(self):
        root = self.make_root()
        code, snap, _, err = self.resolve_with_path(root, make_stub_bin(()))
        self.assertEqual(code, 0, err)
        for name in ("release", "deploy", "knowledge.context", "knowledge.hints"):
            with self.subTest(capability=name):
                self.assertEqual(snap["capabilities"][name]["state"], "unsupported")

    @unittest.skipIf(hasattr(os, "geteuid") and os.geteuid() == 0,
                     "mode bits do not bind root")
    def test_worktrees_is_blocked_when_the_worktree_parent_is_unwritable(self):
        root = self.make_root()
        stub = make_stub_bin(("gh", "git", "just", "codex"))
        # The parent of `.worktrees` is the checkout itself: a read-only
        # checkout is the failure this prerequisite exists to catch.
        parent = root
        original = parent.stat().st_mode
        parent.chmod(0o500)
        try:
            code, snap, _, err = self.resolve_with_path(root, stub)
        finally:
            parent.chmod(original)
        self.assertEqual(code, 0, err)
        entry = snap["capabilities"]["worktrees"]
        self.assertEqual(entry["state"], "blocked")
        self.assertEqual(entry["reason_code"], "vcs_worktree_unsupported")

    def test_worktrees_is_available_when_the_worktree_root_is_absent(self):
        """The worktree root is created on first use, so its absence is normal.

        `.worktrees` is ignored by git and therefore missing from every fresh
        clone; blocking on it would report a working capability as broken.
        """
        root = self.make_root()
        stub = make_stub_bin(("gh", "git", "just", "codex"))
        shutil.rmtree(root / ".worktrees")
        code, snap, _, err = self.resolve_with_path(root, stub)
        self.assertEqual(code, 0, err)
        entry = snap["capabilities"]["worktrees"]
        self.assertEqual(entry["state"], "available")
        self.assertIsNone(entry["reason_code"])
        self.assertIsNone(entry["repair_id"])

    def test_a_relative_executable_resolves_against_its_command_cwd(self):
        """DISC-001: the base is the entry's `cwd`, not `project.root`."""
        source = source_contract()
        source["bindings"]["commands"]["local-check"] = {
            "argv": ["./check"], "cwd": "tools", "env": []}
        source["bindings"]["workflow"]["verification"] = ["local-check"]
        root = self.make_root(source)
        stub = make_stub_bin(("gh", "git", "just", "codex"))

        (root / "tools").mkdir()
        code, snap, _, err = self.resolve_with_path(root, stub)
        self.assertEqual(code, 0, err)
        self.assertEqual(snap["capabilities"]["verification"]["state"], "blocked")

        target = root / "tools" / "check"
        target.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        target.chmod(target.stat().st_mode | stat.S_IXUSR)
        code, snap, _, err = self.resolve_with_path(root, stub)
        self.assertEqual(code, 0, err)
        self.assertEqual(snap["capabilities"]["verification"]["state"], "available")

    def test_a_relative_executable_at_the_root_does_not_satisfy_a_cwd_entry(self):
        source = source_contract()
        source["bindings"]["commands"]["local-check"] = {
            "argv": ["./check"], "cwd": "tools", "env": []}
        source["bindings"]["workflow"]["verification"] = ["local-check"]
        root = self.make_root(source)
        (root / "tools").mkdir()
        decoy = root / "check"
        decoy.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        decoy.chmod(decoy.stat().st_mode | stat.S_IXUSR)
        stub = make_stub_bin(("gh", "git", "just", "codex"))
        code, snap, _, err = self.resolve_with_path(root, stub)
        self.assertEqual(code, 0, err)
        self.assertEqual(snap["capabilities"]["verification"]["state"], "blocked")


class ContradictionTest(ResolverTestCase):
    def refuse(self, contract: dict) -> dict:
        code, payload, _ = self.resolve(self.make_root(contract))
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "invalid_contract")
        return payload["error"]

    def test_supported_tracker_with_kind_none_is_a_contract_error(self):
        contract = source_contract()
        contract["bindings"]["tracker"]["kind"] = "none"
        self.assertIn("/bindings/tracker/kind",
                      [v["pointer"] for v in self.refuse(contract)["violations"]])

    def test_supported_tracker_with_an_empty_cli_is_a_contract_error(self):
        contract = source_contract()
        contract["bindings"]["tracker"]["cli"] = ""
        self.refuse(contract)

    def test_supported_worktrees_with_a_non_git_vcs_is_a_contract_error(self):
        contract = source_contract()
        contract["bindings"]["vcs"]["kind"] = "hg"
        self.refuse(contract)

    def test_supported_knowledge_with_an_empty_path_list_is_a_contract_error(self):
        contract = source_contract()
        contract["bindings"]["paths"]["standards"] = []
        self.assertIn("/bindings/paths/standards",
                      [v["pointer"] for v in self.refuse(contract)["violations"]])

    def test_supported_verification_with_no_ids_is_a_contract_error(self):
        contract = source_contract()
        contract["bindings"]["workflow"]["verification"] = []
        self.refuse(contract)

    def test_supported_review_with_a_null_id_is_a_contract_error(self):
        contract = source_contract()
        contract["bindings"]["workflow"]["review"]["plan"] = None
        self.refuse(contract)

    def test_unsupported_capabilities_impose_no_binding_requirement(self):
        contract = source_contract()
        self.assertEqual(contract["capabilities"]["release"]["support"], "unsupported")
        self.assertIsNone(contract["bindings"]["workflow"]["release"])
        self.assertEqual(contract["bindings"]["deploy"]["adapter"], "none")
        code, _, err = self.resolve(self.make_root(contract))
        self.assertEqual(code, 0, err)

    def test_a_supported_deploy_needs_an_adapter_and_a_command(self):
        contract = source_contract()
        contract["capabilities"]["deploy"]["support"] = "supported"
        self.refuse(contract)


class RequireTest(ResolverTestCase):
    def test_requiring_an_unsupported_capability_refuses(self):
        root = self.make_root()
        code, out, _ = run_with_path(
            str(make_stub_bin(("gh", "git", "just", "codex"))),
            "resolve", "--repo-root", str(root), "--require", "release")
        payload = json.loads(out)
        self.assertEqual(code, 2)
        error = payload["error"]
        self.assertEqual(error["code"], "capability_unavailable")
        self.assertEqual([v["pointer"] for v in error["violations"]],
                         ["/capabilities/release"])
        self.assertEqual(error["repair_id"], "capability.release.unsupported")
        self.assertNotIn("schema_version", payload)

    def test_requiring_a_blocked_capability_names_its_reason_code(self):
        root = self.make_root()
        code, out, _ = run_with_path(
            str(make_stub_bin(("git", "just", "codex"))),
            "resolve", "--repo-root", str(root), "--require", "tracker")
        error = json.loads(out)["error"]
        self.assertEqual(code, 2)
        self.assertEqual(error["code"], "capability_unavailable")
        self.assertEqual(error["repair_id"], "capability.tracker.tracker_cli_missing")

    def test_several_offending_requirements_are_reported_in_pointer_order(self):
        root = self.make_root()
        code, out, _ = run_with_path(
            str(make_stub_bin(("gh", "git", "just", "codex"))),
            "resolve", "--repo-root", str(root),
            "--require", "release", "--require", "deploy")
        error = json.loads(out)["error"]
        self.assertEqual(code, 2)
        pointers = [v["pointer"] for v in error["violations"]]
        self.assertEqual(pointers, ["/capabilities/deploy", "/capabilities/release"])
        self.assertEqual(error["repair_id"], "capability.deploy.unsupported")

    def test_requiring_an_available_capability_returns_the_snapshot(self):
        root = self.make_root()
        code, out, err = run_with_path(
            str(make_stub_bin(("gh", "git", "just", "codex"))),
            "resolve", "--repo-root", str(root), "--require", "tracker")
        self.assertEqual(code, 0, err)
        self.assertEqual(json.loads(out)["schema_version"], 1)

    def test_an_unknown_require_name_is_an_argparse_usage_error(self):
        root = self.make_root()
        code, out, err = run("resolve", "--repo-root", str(root),
                             "--require", "orchestration")
        self.assertEqual(code, 2)
        self.assertEqual(out, "")
        self.assertIn("orchestration", err)


class NoSubprocessTest(ResolverTestCase):
    def test_readiness_runs_no_child_process(self):
        """An empty PATH must still produce a snapshot, not an execution error."""
        root = self.make_root()
        code, out, err = run_with_path(
            str(make_stub_bin(())), "resolve", "--repo-root", str(root))
        self.assertEqual(code, 0, err)
        self.assertEqual(err, "")
        self.assertEqual(json.loads(out)["schema_version"], 1)


class WriteProjectionsTest(ResolverTestCase):
    def write(self, root: Path) -> tuple[int, object, str]:
        code, out, err = run("write-projections", "--repo-root", str(root))
        try:
            payload: object = json.loads(out)
        except json.JSONDecodeError:
            payload = None
        return code, payload, err

    def actions(self, payload: object) -> dict:
        return {p["id"]: p["action"] for p in payload["projections"]}

    def test_a_fresh_root_writes_both_projections(self):
        root = self.make_root(projections=False)
        code, payload, err = self.write(root)
        self.assertEqual(code, 0, err)
        self.assertEqual(sorted(payload), ["projections"])
        self.assertEqual(self.actions(payload),
                         {"codex.entry": "written", "claude.entry": "written"})
        self.assertTrue((root / "AGENTS.md").is_file())

    def test_the_codex_target_is_header_blank_line_then_the_source(self):
        root = self.make_root(projections=False)
        source = (root / ".agents" / "instructions" / "bootstrap.md").read_bytes()
        self.assertEqual(self.write(root)[0], 0)
        rendered = (root / "AGENTS.md").read_bytes()
        self.assertEqual(rendered, CODEX_HEADER.encode() + b"\n\n" + source)

    def test_the_claude_target_keeps_its_authored_body_and_gains_one_line(self):
        root = self.make_root(projections=False)
        body = (root / "CLAUDE.md").read_text("utf-8")
        self.assertEqual(self.write(root)[0], 0)
        after = (root / "CLAUDE.md").read_text("utf-8")
        self.assertIn(body, after)
        self.assertEqual(after.splitlines().count(MANAGED_LINE), 1)

    def test_a_second_run_reports_unchanged_and_touches_no_mtime(self):
        root = self.make_root(projections=False)
        self.assertEqual(self.write(root)[0], 0)
        before = {name: (root / name).stat().st_mtime_ns
                  for name in ("AGENTS.md", "CLAUDE.md")}
        code, payload, err = self.write(root)
        self.assertEqual(code, 0, err)
        self.assertEqual(self.actions(payload),
                         {"codex.entry": "unchanged", "claude.entry": "unchanged"})
        after = {name: (root / name).stat().st_mtime_ns
                 for name in ("AGENTS.md", "CLAUDE.md")}
        self.assertEqual(before, after)

    def test_a_hand_edited_codex_target_is_rewritten(self):
        root = self.make_root()
        self.assertEqual(self.write(root)[0], 0)
        (root / "AGENTS.md").write_bytes(b"hand written\n")
        code, payload, err = self.write(root)
        self.assertEqual(code, 0, err)
        self.assertEqual(self.actions(payload)["codex.entry"], "written")
        source = (root / ".agents" / "instructions" / "bootstrap.md").read_bytes()
        self.assertEqual((root / "AGENTS.md").read_bytes(),
                         CODEX_HEADER.encode() + b"\n\n" + source)

    def test_a_missing_claude_target_is_created_holding_only_the_line(self):
        root = self.make_root()
        (root / "CLAUDE.md").unlink()
        contract = source_contract()
        contract["bindings"]["paths"]["architecture"] = ["AGENTS.md"]
        (root / ".agents" / "project.json").write_text(
            json.dumps(contract), encoding="utf-8")
        self.assertEqual(self.write(root)[0], 0)
        self.assertEqual((root / "CLAUDE.md").read_text("utf-8"),
                         MANAGED_LINE + "\n")

    def test_a_duplicated_managed_line_is_refused_and_not_rewritten(self):
        root = self.make_root()
        (root / "CLAUDE.md").write_text(
            f"# body\n{MANAGED_LINE}\nmore\n{MANAGED_LINE}\n", encoding="utf-8")
        before = (root / "CLAUDE.md").read_text("utf-8")
        code, payload, _ = self.write(root)
        self.assertEqual(code, 2)
        error = payload["error"]
        self.assertEqual(error["code"], "invalid_projection")
        self.assertEqual(error["repair_id"], "projection.claude.entry.stale")
        self.assertEqual([v["pointer"] for v in error["violations"]],
                         ["/projections/claude.entry"])
        self.assertEqual((root / "CLAUDE.md").read_text("utf-8"), before)

    def test_a_missing_source_is_a_contract_error(self):
        root = self.make_root()
        (root / ".agents" / "instructions" / "bootstrap.md").unlink()
        code, payload, _ = self.write(root)
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "invalid_contract")
        self.assertEqual(payload["error"]["repair_id"],
                         "contract.projections.source_missing")

    def test_rendering_is_deterministic_across_runs(self):
        root = self.make_root()
        self.assertEqual(self.write(root)[0], 0)
        first = (root / "AGENTS.md").read_bytes()
        (root / "AGENTS.md").unlink()
        self.assertEqual(self.write(root)[0], 0)
        self.assertEqual((root / "AGENTS.md").read_bytes(), first)

    def test_a_write_preserves_the_targets_permission_bits(self):
        """The atomic replace must not narrow the mode tempfile creates at."""
        root = self.make_root(projections=False)
        # 0750, a mode no other actor here produces: under the umask below a
        # created file lands on 0644 and `tempfile` creates at 0600, so an
        # implementation that ignored the existing target's bits — whichever
        # of those two it fell back to — fails this assertion instead of
        # matching it by coincidence (COR-004).
        os.chmod(root / "CLAUDE.md", 0o750)
        # The child inherits this umask, so the created target's mode is a
        # fixed expectation rather than whatever the machine happens to set.
        previous = os.umask(0o022)
        self.addCleanup(os.umask, previous)
        self.assertEqual(self.write(root)[0], 0)
        kept = (root / "CLAUDE.md").stat().st_mode & 0o777
        self.assertEqual(oct(kept), oct(0o750))
        created = (root / "AGENTS.md").stat().st_mode & 0o777
        self.assertEqual(oct(created), oct(0o644))
        self.assertTrue(created & stat.S_IRGRP and created & stat.S_IROTH,
                        oct(created))

    def test_no_stray_temporary_file_survives_a_write(self):
        root = self.make_root(projections=False)
        before = sorted(path.name for path in root.iterdir())
        self.assertEqual(self.write(root)[0], 0)
        self.assertEqual(sorted(path.name for path in root.iterdir()),
                         sorted([*before, "AGENTS.md"]))

    def test_a_failed_replace_leaves_no_temporary_file_behind(self):
        """A non-empty directory cannot be replaced by a file, so the write
        fails with the temporary file already on disk."""
        root = self.make_root(projections=False)
        (root / "AGENTS.md").mkdir()
        (root / "AGENTS.md" / "occupant").write_text("x", encoding="utf-8")
        before = sorted(path.name for path in root.iterdir())
        code, _, _ = self.write(root)
        self.assertEqual(code, 2)
        self.assertEqual(sorted(path.name for path in root.iterdir()), before)


class CommittedProjectionTest(ResolverTestCase):
    def test_the_repository_projections_are_present_and_current(self):
        agents = (REPO_ROOT / "AGENTS.md").read_bytes()
        source = (REPO_ROOT / ".agents" / "instructions" / "bootstrap.md").read_bytes()
        self.assertEqual(agents, CODEX_HEADER.encode() + b"\n\n" + source)
        claude = (REPO_ROOT / "CLAUDE.md").read_text("utf-8")
        self.assertEqual(claude.splitlines().count(MANAGED_LINE), 1)


class CheckProjectionsTest(ResolverTestCase):
    def check(self, root: Path) -> tuple[int, object, str]:
        code, out, err = run("check-projections", "--repo-root", str(root))
        try:
            payload: object = json.loads(out)
        except json.JSONDecodeError:
            payload = None
        return code, payload, err

    def test_in_sync_reports_every_projection_unchanged(self):
        code, payload, err = self.check(self.make_root())
        self.assertEqual(code, 0, err)
        self.assertEqual(sorted(payload), ["projections"])
        self.assertEqual({p["action"] for p in payload["projections"]}, {"unchanged"})
        self.assertEqual([p["id"] for p in payload["projections"]],
                         ["codex.entry", "claude.entry"])

    def test_an_appended_byte_in_the_codex_target_is_drift(self):
        root = self.make_root()
        with (root / "AGENTS.md").open("a", encoding="utf-8") as handle:
            handle.write("\nhand edit\n")
        code, payload, _ = self.check(root)
        self.assertEqual(code, 2)
        error = payload["error"]
        self.assertEqual(error["code"], "invalid_projection")
        self.assertEqual([v["pointer"] for v in error["violations"]],
                         ["/projections/codex.entry"])
        self.assertEqual(error["repair_id"], "projection.codex.entry.stale")

    def test_a_missing_codex_target_is_drift(self):
        root = self.make_root()
        (root / "AGENTS.md").unlink()
        code, payload, _ = self.check(root)
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["repair_id"], "projection.codex.entry.missing")

    def test_a_deleted_managed_line_is_drift(self):
        root = self.make_root()
        (root / "CLAUDE.md").write_text("# authored body\n", encoding="utf-8")
        code, payload, _ = self.check(root)
        self.assertEqual(code, 2)
        error = payload["error"]
        self.assertEqual([v["pointer"] for v in error["violations"]],
                         ["/projections/claude.entry"])
        self.assertEqual(error["repair_id"], "projection.claude.entry.stale")

    def test_a_duplicated_managed_line_is_drift(self):
        root = self.make_root()
        with (root / "CLAUDE.md").open("a", encoding="utf-8") as handle:
            handle.write(MANAGED_LINE + "\n")
        code, payload, _ = self.check(root)
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "invalid_projection")

    def test_both_drifted_projections_are_reported_in_pointer_order(self):
        root = self.make_root()
        (root / "AGENTS.md").unlink()
        (root / "CLAUDE.md").write_text("# authored body\n", encoding="utf-8")
        code, payload, _ = self.check(root)
        self.assertEqual(code, 2)
        self.assertEqual([v["pointer"] for v in payload["error"]["violations"]],
                         ["/projections/claude.entry", "/projections/codex.entry"])
        self.assertEqual(payload["error"]["repair_id"],
                         "projection.claude.entry.stale")

    def test_a_missing_source_is_a_contract_error_not_drift(self):
        root = self.make_root()
        (root / ".agents" / "instructions" / "bootstrap.md").unlink()
        code, payload, _ = self.check(root)
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "invalid_contract")

    def test_check_projections_writes_nothing(self):
        """SF-001: the same three witnesses Task 1's `ReadOnlyTest` uses."""
        assert_read_only(self, self.make_root(), 0, "check-projections")

    def test_a_refusing_check_projections_writes_nothing(self):
        root = self.make_root()
        with (root / "AGENTS.md").open("a", encoding="utf-8") as handle:
            handle.write("x\n")
        assert_read_only(self, root, 2, "check-projections")

    def test_a_refusing_resolve_on_drift_writes_nothing(self):
        root = self.make_root()
        with (root / "AGENTS.md").open("a", encoding="utf-8") as handle:
            handle.write("x\n")
        assert_read_only(self, root, 2, "resolve")


class ResolveFreshnessTest(ResolverTestCase):
    def test_resolve_refuses_a_drifted_projection_with_no_snapshot(self):
        root = self.make_root()
        with (root / "AGENTS.md").open("a", encoding="utf-8") as handle:
            handle.write("hand edit\n")
        code, out, _ = run("resolve", "--repo-root", str(root))
        self.assertEqual(code, 2)
        payload = json.loads(out)
        self.assertEqual(sorted(payload), ["error"])
        self.assertEqual(payload["error"]["code"], "invalid_projection")
        for member in ("schema_version", "project", "bindings", "capabilities"):
            self.assertNotIn(f'"{member}"', out)

    def test_resolve_refuses_a_deleted_managed_line(self):
        root = self.make_root()
        (root / "CLAUDE.md").write_text("# authored body\n", encoding="utf-8")
        code, payload, _ = self.resolve(root)
        self.assertEqual(code, 2)
        self.assertEqual(payload["error"]["code"], "invalid_projection")

    def test_resolve_still_writes_nothing_when_it_refuses(self):
        root = self.make_root()
        (root / "AGENTS.md").unlink()
        before = sorted(str(p.relative_to(root)) for p in root.rglob("*"))
        self.assertEqual(self.resolve(root)[0], 2)
        after = sorted(str(p.relative_to(root)) for p in root.rglob("*"))
        self.assertEqual(before, after)


class DriftGateTest(ResolverTestCase):
    """Seam 9: this repository's own committed contract must resolve."""

    def test_the_repository_resolves_and_its_projections_are_current(self):
        code, out, err = run("resolve", "--repo-root", str(REPO_ROOT))
        self.assertEqual(code, 0, err or out)
        snapshot = json.loads(out)
        self.assertEqual(snapshot["schema_version"], 1)
        self.assertEqual(sorted(snapshot["capabilities"]), sorted(CAPABILITY_NAMES))
        self.assertEqual(snapshot["project"]["id"], "fagenorn/nix-config")
        self.assertEqual(snapshot["project"]["root"], str(REPO_ROOT))

    def test_the_repository_check_projections_is_clean(self):
        code, out, err = run("check-projections", "--repo-root", str(REPO_ROOT))
        self.assertEqual(code, 0, err or out)
        self.assertEqual({p["action"] for p in json.loads(out)["projections"]},
                         {"unchanged"})


if __name__ == "__main__":
    unittest.main()
